### ISSUE TITLE
Consider implementing engine abstraction

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#135]
When mixing TF and TFE you can end up writing basically the same code twice for models. By having some abstract that can be either TF or TFE that code could be reused.

Smallest change needed is possibly just to finish #105 and then pass either `tf` or a protocol instance. An extension of that could be to add functions to `tfe` that get redirected to the current protocol.

**Comment by ianlivingstone** [comment]
Is it possible for a user to just write the model/code in TF and then we use the TF API to translate it into TFE (e.g. regenerate the graph for an encrypted setting)?

**Comment by mortendahl** [comment]
it's worth a try but not sure how good the tf inspection api is

**Comment by ianlivingstone** [comment]
It's definitely worth investigating, we'd have a much smaller footprint as a result!

**Comment by mortendahl** [comment]
not sure i follow?

**Comment by ianlivingstone** [comment]
> not sure i follow re smaller footprint?

Less for a user to learn as they could just take their pre-existing knowledge of tf, then pass the built graph into tfe and get back a converted graph. We'd still offer all of the underlying API we have today but this could be the first step for anyone who just wants to get running with "encrypted" machine learning.

**Comment by mortendahl** [comment]
gotcha

fyi if we expose all ops on the tfe module that it'd just be a matter of replacing e.g. `tf.matmul` with `tfe.matmul`, or if you're very ambitious, replacing `import tensorflow as tf` with `import tensorflow_encrypted as tf`

**Comment by mortendahl** [comment]
related to #149

**Comment by jvmancuso** [comment]
maybe we can close this given current discussions around API simplification? i.e. #262

**Comment by mortendahl** [comment]
@jvmancuso suggest we keep it around to not forget; the issue discussed here isn't mentioned in the other issues afaict

**Comment by mortendahl** [comment]
Closing in favour of #473
