### ISSUE TITLE
Implement and bench long multiplication tensor

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#145]
Approach where each limb is in a separate tensor and mul+matmul is done accordingly. Would like to see performance compared to CRT for typical computations involving both matmul, truncation, and sampling.

**Comment by mortendahl** [comment]
To get ~100bit precision using int32s we might end up with roughly the same number of components as in CRT (~10), so unless there's a way to avoid exploding the number of matmuls (~10^2) I'm leaning towards CRT. Should still be explored but maybe back burner for now, or until something pops up to avoid explosion.

**Comment by zicofish** [comment]
In the most recent [benchmark](https://github.com/tf-encrypted/tf-encrypted), 64 bit is already enough for most cases: inference, training, etc. So 100 bit should probably be removed in the future. Moreover, if larger bit size is needed, a native 128-bit support should be used, but not the CRT 100 bit which is too slow.
