### ISSUE TITLE
Finish conv2d

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#17]
Some combinations for Pond's `conv2d` is missing.

**Comment by kamathhrishi** [comment]
Could you elaborate more on what's missing?

**Comment by justin1121** [comment]
I believe the backward pass is what is missing. There is a branch open with some initial work here https://github.com/mortendahl/tf-encrypted/pull/156, might need to coordinate with @koenvanderveen  to find out more!

**Comment by justin1121** [comment]
There is also some work being done related to conv1d and might require some changes to the current conv2d implementation that could effect the backward pass. @jvmancuso or @yanndupis might have more information regarding this.

**Comment by jvmancuso** [comment]
Any changes for conv1d can adapt to what's done in the meantime.  We're not entirely sure we'll need to change conv2d, but there's a lot to be done before we would need to modify conv2d, if at all.

**Comment by jvmancuso** [comment]
I think pushing forward on the backwards pass for conv2d as in #156 would be super helpful to us!

**Comment by vincehong** [comment]
ABY3 protocol now has fully functional NN training.
