### ISSUE TITLE
Implement Division

### ISSUE THREAD

**Issue by bendecoste** [tf-encrypted/tf-encrypted#258]
Related #106.

This main concerns is that we would still not have true softmax with division (missing `exp`) and that the implementation will create a ton of nodes in the graph.

Since we have no immediate need for it, and it will be quite expensive, it will be deferred.

**Comment by vincehong** [comment]
ABY3 now have true softmax with division. 
https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/protocol/aby3/aby3.py#L1672
