### ISSUE TITLE
Converter - Fuse higher level tf ops to gain MPC optimizations

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#297]
The main idea here is that i'd be great if we could take a higher level tf ops (e.g. tf.layers.conv1d) which are composed of many different base ops and recognize that we can convert that group of ops into a single tf-encrypted implementation. Currently, all we can do is convert one base op at a time without any knowledge of what those ops are actually doing. There was already some discussion elsewhere that I will copy into this issue 😄.

**Comment by justin1121** [comment]
From: @jvmancuso:

The idea was that you could have a layer in TF that doesn't come wrapped nicely in it's own scope in the computation graph (e.g. conv1d), so there's no obvious way for us to be able to recognize that group of ops as a single higher-level op.  This means that if there were optimizations/customizations we want to compute conv1d faster in MPC, there's no simple way for us to convert a plaintext graph with that op to include that optimized version.  We'd be stuck with recognizing each sub-op of conv1d and trying to find specific optimizations for each of those ops.  In this particular case, `tf.layers.conv1d` always comes with `expand_dims`, `squeeze`, and a `convd2d`, but in some cases it comes with extra ops like `required_space_to_batch_paddings`, `batch_to_space_nd`, and `space_to_batch_nd`. If we wanted to treat the whole group as a conv1d op to make specific customizations to the high-level implementation on our end, that seems nontrivial with the current converter.

**Comment by justin1121** [comment]
From @mortendahl:

@jvmancuso could we use heuristics to identify conv1d etc in the protobuf files? I can't find anything in the protobuf files that gives us the composition explicitly, but as long as people have not used too many custom names it seems that we could make qualified guesses. wdyt?

**Comment by justin1121** [comment]
From me:

> but as long as people have not used too many custom names it seems that we could make qualified guesses

I worry about exactly this happening. It might be a fine workaround for now but there will probably be a time when someone uses a custom name that messes with our heuristics. One idea I had was that we could make a wrapper around some of the tensorflow ops which all it does is adds a super custom name that somehow relates to tfe so that it would be even more unlikely that somehow would clash with them.

**Comment by justin1121** [comment]
From @jvmancuso:

>One idea I had was that we could make a wrapper around some of the tensorflow ops which all it does is adds a super custom name that somehow relates to tfe so that it would be even more unlikely that somehow would clash with them.

I had this thought as well, but I dislike all solutions that assume a user's scoping behavior.  Whether we require or forbid that they wrap their op in a particular scope, both seem damaging to a seamless converter.

However, I don't think the heuristics solution @mortendahl proposed has this problem -- if we think of these heuristics as patterns that we want to match, we can delay converting each node that matches a stored pattern until the pattern breaks or is complete.  If it breaks, we immediately convert all the previous nodes one-by-one, but if it's completed, then we evaluate whatever custom conversion logic we've defined for that pattern.

This subverts the name-scoping problem, since when we want to recognize a specific heuristic, we can safely assume it's been built up from a standard collection of ops (e.g. a `tf.layers` function or class), so that scopes will be standardized.  Otherwise, we'd handle it by converting ops one-by-one, so the scoping problem is handled there too.

The only problem I foresee is sustainability, building up these patterns seems like a long-term project and the underlying patterns could change, as they wouldn't qualify under the TF API stability guarantees.

**Comment by justin1121** [comment]
From me:

> I had this thought as well, but I dislike all solutions that assume a user's scoping behavior. Whether we require or forbid that they wrap their op in a particular scope, both seem damaging to a seamless converter.

I'm not sure that it's unreasonable that the users have to use tfe helper functions to get the most optimized functions out of tfe. It's not ideal that users must train using these helpers function instead of pure tf but the engineering effort would be drastically smaller compared to this other heuristic approach. Also it would be totally sustainable by us.

It's also not clear to me that @mortendahl's solution subverts the name scoping problem. Think a concrete example would help. 😄

**Comment by jvmancuso** [comment]
Note we've already started this one in work related to #200!  Currently in the branch `required_space2`

**Comment by mortendahl** [comment]
@jvmancuso is this already done?
