### ISSUE TITLE
High-level API

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#403]
Moving forward the idea is to have two APIs:

- a high level API as close as possible to keras:

  - allowing user to more clearly express what they want to achieve with secure computation (along the lines of how TF2 wraps distribution up into a `DistributionStrategy` object) 

  - making it easier for us to guide users in how to get good performance out of TFE, in some sense making it harder for them to shoot themselves in the foot

- a low level API similar to what exists currently:

  - gives full power but also the ability to shoot yourself in the foot by eg naively using expensive operations everywhere

See also [Standardizing on Keras: Guidance on High-level APIs in TensorFlow 2.0](https://medium.com/tensorflow/standardizing-on-keras-guidance-on-high-level-apis-in-tensorflow-2-0-bad2b04c819a)

**Comment by mortendahl** [comment]
```python
model = tf.keras.Sequential([
  layers.Dense(64, activation=’relu’)
  layers.Dense(64, activation=’relu’)
  layers.Dense(10, activation=’softmax’)
])

model.compile(
  optimizer=’adam’,
  loss=’sparse_categorical_crossentropy’,
  metrics=[‘accuracy’])

model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test, y_test)
```

**Comment by mortendahl** [comment]
![training](https://user-images.githubusercontent.com/5921097/53163104-aab3f900-35cd-11e9-918b-4f915d4e5122.png)
![prediction](https://user-images.githubusercontent.com/5921097/53163115-ae478000-35cd-11e9-8129-58822073be92.png)

**Comment by mortendahl** [comment]
![federated](https://user-images.githubusercontent.com/5921097/53171866-320c6700-35e4-11e9-9602-a6a91fe4059f.png)

**Comment by mortendahl** [comment]
Federated models:

![federated](https://user-images.githubusercontent.com/5921097/53172000-90d1e080-35e4-11e9-8457-753df6dc3073.png)

**Comment by mortendahl** [comment]
```python
model = tf.keras.Sequential([
  tf.keras.layers.Dense(64, activation=’relu’)
  tf.keras.layers.Dense(64, activation=’relu’)
  tf.keras.layers.Dense(10, activation=’softmax’)
])

model.compile(
  optimizer=’adam’,
  loss=’sparse_categorical_crossentropy’,
  metrics=[‘accuracy’],
  computation='aby3')

model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test, y_test)

model.predict(x)
```

**Comment by mortendahl** [comment]
Custom [Keras backends](https://keras.io/backend/):
> In Keras it is possible to load more backends than "tensorflow", "theano", and "cntk". Keras can use external backends as well, and this can be performed by changing the keras.json configuration file, and the "backend" setting. Suppose you have a Python module called my_module that you wanted to use as your external backend. The keras.json configuration file would be changed as follows: ... An external backend must be validated in order to be used, a valid backend must have the following functions: placeholder, variable and function.

See also [here](https://www.tensorflow.org/api_docs/python/tf/keras/backend)

**Comment by justin1121** [comment]
I had this same idea about just creating a new keras backend. I mostly worry about the keras frontend being flexible enough for our uses and how much we'd have to implement to get simple models to work correctly. It could be something we could test fairly easily though. We just implement those three functions (`placeholder`, `variable` and `function`) and then implement a simple `Sequential` model with a single `Dense` layer. We could try running that and see what breaks. Perhaps a medium-term goal rather than short-term.

**Comment by mortendahl** [comment]
Note: let's make sure that `tfe.keras` matches `tf.keras` as much as possible, ideally such that one can simply replace `tf` with `tfe`.

**Comment by mortendahl** [comment]
One small note: it seems safe to follow design patterns that users will be familiar with from TF already, even if there might potentially be better ways of doing things. One concrete example is how to make this Keras implementation agnostic to the underlying computation protocol, which can be done in at least two ways:

- define abstract Keras elements that can be created without knowing the computation protocol and later instantiated in an explicit call; one issue here is the Keras functional API which might require us to replicate a lot of dummy elements and patch up;

- an alternative is to take inspiration from TF distribution strategies and allow the use of contexts; to still be agnostic to the computation protocol the user can wrap model creation in a function

cc @yanndupis @jvmancuso

**Comment by mortendahl** [comment]
Closing, with protocol requirements distilled into https://github.com/tf-encrypted/tf-encrypted/issues/558.
