### ISSUE TITLE
Move test files next to implementation files

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#410]
Right now we have (almost) all tests files in the `/tests/` subdirectory, yet it seems more logical and convenient to keep them next to the corresponding code they're testing. This issue is about simply moving those files (with `git mv`) and patching any imports that may need it.

**Comment by ianlivingstone** [comment]
What is the python standard?

**Comment by justin1121** [comment]
Interesting discussion here https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules. I think tensorflow privacy/federated are doing them inline might be good to match what they're doing. Also makes most sense to me so we don't have to expose internal module functions to be able to test them.

**Comment by mortendahl** [comment]
This shows the layout I have in mind: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/ops, i.e. `impl_test.py` right next to `impl.py`

**Comment by jvmancuso** [comment]
Think this is part of a Google or TF style guide, although can't find a good link for it

**Comment by jvmancuso** [comment]
Note, testing files should be stylized according to the TF style guide (pylintrc file) in #474 as they're moved into the main `tf_encrypted` package (or any other package that's being run during the lint part of the Makefile)
