### ISSUE TITLE
Switching to TensorFlow style guide

### ISSUE THREAD

**Issue by jvmancuso** [tf-encrypted/tf-encrypted#424]
We should consider switching to the [TensorFlow style guide](https://www.tensorflow.org/community/contribute/code_style).  It's essentially the same as Google's style guide for Python, with a few exceptions.  The rest of the TensorFlow ecosystem already follows this guide for their Python code.  Here's an incomplete list of some things that would change:
- PEP8 linting with pylint instead of flake8 (they provide a specific [pylintrc file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/pylintrc) to use for checking code quality that we can also use)
- Files with unit tests live inside the modules they test (#410)
- Switching the interpreted tab length from 4 spaces to 2 spaces
- Line length reduced to 79 from 99 (made easier by the reduction in tab length)

Someone should be assigned this and own it if we decide to proceed.  I'd be willing to volunteer if nobody finds fixing linter errors particularly engaging :D

**Comment by mortendahl** [comment]
Not immediately a fan of the latter two but think we should do this to get into the habit
