### ISSUE TITLE
Using `with protocol` doesn't work

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#439]
The following should work but doesn't (work relu function):

```python
x = tfe.define_private_variable(tf.constant([1,2,3,4]))
y = tfe.define_private_variable(tf.constant([1,2,3,4]))

with tfe.protocol.Pond():
    print(tfe.relu, tfe.get_protocol())
    approx = tfe.relu(x)
    
with tfe.protocol.SecureNN():
    print(tfe.relu, tfe.get_protocol())
    exact = tfe.relu(y)
```

Instead you currently have to do:

```python
x = tfe.define_private_variable(tf.constant([1,2,3,4]))
y = tfe.define_private_variable(tf.constant([1,2,3,4]))

tfe.set_protocol(tfe.protocol.Pond())
print(tfe.relu, tfe.get_protocol())
approx = tfe.relu(x)
    
tfe.set_protocol(tfe.protocol.SecureNN())
print(tfe.relu, tfe.get_protocol())
exact = tfe.relu(y)
```

**Comment by jvmancuso** [comment]
This should be easy to make.  Let's try to hold off on it until the style guide fixes are in? (#424)

**Comment by mortendahl** [comment]
Yeah I agree on both accounts

**Comment by ianlivingstone** [comment]
@mortendahl can you provide more details around why we need to make this change and how to do it?

**Comment by mortendahl** [comment]
Mixing functionality has been on the map for a while, definitely something we want. This fits into the refactoring work though.

**Comment by mortendahl** [comment]
Should have been fixed as part of https://github.com/tf-encrypted/tf-encrypted/pull/755
