### ISSUE TITLE
Switch layers to tf.keras spec

### ISSUE THREAD

**Issue by jvmncs** [tf-encrypted/tf-encrypted#441]
Related #416, #388 

We'd like to refactor our layers module to match the keras api spec.  I'll work on this once the style guide PR has been submitted (#424)

**Comment by yanndupis** [comment]
@jvmancuso I think we can close this issue?

**Comment by jvmancuso** [comment]
I'm not sure we should close this until the tfe.layers module is gone :)

**Comment by ianlivingstone** [comment]
@jvmancuso could you add any colour relate to switching tfe.layers over to keras.

**Comment by zjn-code** [comment]
We remove tfe.layers in TFE based on TF2.
