### ISSUE TITLE
[focus] Keras

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#470]
We want to expose a Keras-like API for TF Encrypted, for both prediction and training. Goal is to stay as close as possible to TensorFlow's Keras.

Join development conversation in https://tf-encrypted.slack.com/archives/CJGFV71DF/p1557830297001500

**Comment by zjn-code** [comment]
Now, tfe.keras implement a lot layers in tf.keras.layers, several losses and optimizers, and we will add more keras-like api to TFE, maybe this issue could be closed.
