### ISSUE TITLE
Private vs. public encoding methods

### ISSUE THREAD

**Issue by jvmancuso** [tf-encrypted/tf-encrypted#477]
Right now, Pond._decode and Pond._encode are stylized as private methods, but we only ever use them as public methods.  I suggest we rename them to Pond.decode and Pond.encode.

**Comment by mortendahl** [comment]
Sure. If I remember correctly then the plan is to turn these into casts with the refactoring, but we can make them public in the meantime

**Comment by jvmancuso** [comment]
On further inspection they are only being used in helper functions that are called from within the `dispatch` method.  I'd argue this makes their usage private, so this is probably more of an instance in which we can ignore the PEP8 rule in pylint whenever it comes up for these methods (also including Pond._reconstruct under this heading).
