### ISSUE TITLE
PySyft Integration

### ISSUE THREAD

**Issue by jvmancuso** [tf-encrypted/tf-encrypted#484]
We want to expose `tfe.keras` in a `syft.keras` package [here](https://github.com/Openmined/PySyft).  This has several dependencies:

**Required**

- Keras API #479 
- Between-graph helpers (i.e. accepting queued inputs) #483 
- `model.share(protocol)` way of converting from plaintext to encrypted model

**Nice to have**

- PySyft model searching

**Comment by mortendahl** [comment]
Closed via https://github.com/OpenMined/PySyft/pull/2170
