### ISSUE TITLE
SecureNN by default

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#493]
Using e.g. ReLU approximations should perhaps be considered an optimization for intermediate users instead of the default. Having SecureNN as default protocol will give worse default performance but be closer to expected results for first-time users.

Partially inspired by https://github.com/tf-encrypted/tf-encrypted/issues/491.

**Comment by bendecoste** [comment]
👍.  I think Pond will lead a lot of new users to believe that the library is not working.

We could perhaps also print a log if the user does not explicitly set a protocol?

**Comment by vincehong** [comment]
As replicated sharing has a superior efficiency in most of the cases, we use ABY3 as default protocol now.
