### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by OutstanderWang** [tf-encrypted/tf-encrypted#506]
Hi!
I'm wondering tf-encrypted support the HE on GPU? Because it only require tensorflow instead of tensorflow-gpu. More importantly, I didn't see any *.cu files about HE. Please let me know if I miss something, thanks!

**Comment by mortendahl** [comment]
Hi @OutstanderWang, there is currently no HE support released but it's definitely on the short term roadmap. Whether or not it'll be on the GPU depends on the specific third-party HE implementations we'll be using. If you're interested in helping out with this I'd love to start a discussion and relay some of the thoughts we already have.

**Comment by mortendahl** [comment]
Closing up, happy to continue the discussion if interest arises.
