### ISSUE TITLE
Module for secure randomness not loaded when installed from PyPI package

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#513]
TFE installed via pip will currently *not* load the secure randomness module. Error seems to come from TensorFlow:

```
>>> secure_random_module = tf.load_op_library(shared_object)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/tfe-release-py35/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/usr/local/miniconda3/envs/tfe-release-py35/lib/python3.5/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.13.1.so, 6): no suitable image found.  Did find:
	/usr/local/miniconda3/envs/tfe-release-py35/lib/python3.5/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.13.1.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/usr/local/miniconda3/envs/tfe-release-py35/lib/python3.5/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.13.1.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

Package should come with this for both Python 3.5 and 3.6 and both Linux and macOS.

**Comment by justin1121** [comment]
Unable to reproduce on macos with python 3.5 and 3.6, linux with python 3.5 and 3.6. Blocked until we have a way to reproduce this reliably.

**Comment by mortendahl** [comment]
Same here, I can't reproduce anymore. Closing down for now. Thanks a lot for looking into it @justin1121!

**Comment by jvmancuso** [comment]
There are reports of PySyft users in the OpenMined Slack experiencing this error: https://openmined.slack.com/archives/C6EEFN3A8/p1559517593068600?thread_ts=1559517593.068600&cid=C6EEFN3A8

**Comment by justin1121** [comment]
Others have had similar issues before https://github.com/bbalasub1/glmnet_python/issues/17. Even the first eight bytes is the same.

**Comment by justin1121** [comment]
I can reproduce the error message macos if I copy over the `.so` file from a ubuntu box. Is pip somehow installing the linux shared object on macos?

**Comment by ianlivingstone** [comment]
> I can reproduce the error message macos if I copy over the .so file from a ubuntu box. Is pip somehow installing the linux shared object on macos?

It could be a bug with how we build the shared object - is it possible we're overwriting the .so we're packaging up with pip?

**Comment by justin1121** [comment]
I can reproduce this consistently by installing tf-encrypted version 0.5.2 (`pip install tf-encrypted==0.5.2`) so this release must be broken. Still stumped on how that version even would get installed for syft users. The version is pinned to tf-encrypted 0.5.4. Perhaps this is happening to users with tf-encrypted already installed and for some reason tf-encrypted 0.5.4 isn't being installed correctly.

**Comment by justin1121** [comment]
Next steps here:

1. Inform people having problems to make sure they have tfe 0.5.4 installed.

2. Update release documentation to explicitly mention to make sure the secure randomness module is being loaded once a release candidate has been pushed.

3. Continue to watch for this problem in future releases, etc. If it's a persistent problem we can't figure out we might have to figure out a different approach to building the shared objects.

**Comment by jvmancuso** [comment]
@justin1121 looks like upgrading to 0.5.4 does not fix the problem. here's another report of a PySyft user who is explicitly using tf 1.13.1 and tfe 0.5.4: https://openmined.slack.com/archives/C6DEWA4FR/p1559656785003600

**Comment by justin1121** [comment]
Ahh secure randomness is not supported on windows.

**Comment by mortendahl** [comment]
Do we even have a pypi package for Windows?

**Comment by justin1121** [comment]
Yeah good point. How did they install tf-encrypted in the first place?!

**Comment by justin1121** [comment]
Looked into how tf-encrypted is getting installed on windows and it looks like it just installs the source tarball if there's no wheel available. I think we should either not upload the tarball or add to the secure randomness warning message that it's not supported on windows.

**Comment by mortendahl** [comment]
Let's do the second option, we (or PySyft) might have some users on Windows, and it's better to give them something than nothing.

**Comment by justin1121** [comment]
Yeah not sure what happened there. Maybe had 0.5.2 installed somehow?

**Comment by mortendahl** [comment]
@justin1121 what do you think about compiling and packaging the custom ops for several versions of TensorFlow? right now you'll only get them if you're on TF 1.13.1 and fall back to insecure randomness for other versions. moving forward we'll have more custom ops, to the point where we might start having strong dependencies on them. from what I understand it could be a simple as updating the build and deploy CI script?

**Comment by justin1121** [comment]
That's what we used to do I think we wanted to force everyone on 1.13.1 to get the faster int64s so we removed it. I think to add new versions to packages all we need to do is add a couple lines here https://github.com/tf-encrypted/tf-encrypted/blob/master/Makefile#L310. For 1.14.0rc0:

```
pip install tensorflow==1.14.0rc0
$(MAKE) $(SECURE_OUT_PRE)1.14.0rc0.so
```

Something we may want to consider is just building the objects on install although that could severely slower the install time (probably why decided to package them together in the first place).

**Comment by mortendahl** [comment]
Excellent, thanks! 

> Something we may want to consider is just building the objects on install although that could severely slower the install time (probably why decided to package them together in the first place).

Building on install seems less ideal to me, as it would require the user to have a suitable build environment.

Another thing, what do you think about splitting up the make file so it scales better with more custom ops? Ie having makefile in subdirectories etc.

**Comment by justin1121** [comment]
Yeah makes sense to me. Not sure why we put it all in one Makefile. I'd actually suggest using bazel to build the custom ops too. Tensorflow provides some pretty good guides for building custom op with bazel.
