### ISSUE TITLE
More robust conv2d

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#53]
The current convolution implementation isn't as robust as the built in tensorflow one. If we're going to be able to import any tensorflow graph we'll need to match the robustness of that implementation. 

Two main issues I've come across:

- tensorflow takes 2 or 4 strides for a 2d convolution. I think right now we only support 1 stride
- tensorflow can support both NCHW and NHWC format whereas we only support NCHW

There are probably other edge cases and at some point we should probably test all the different edge cases.

**Comment by zicofish** [comment]
Various features have been added in the past years. These issues should have been fixed due to the most recent support for ResNet50 inference. We can open a new issue to discuss if necessary.
