### ISSUE TITLE
Investigate possibility of using distribution strategies

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#534]
Distribution strategies are becoming an integral part of TF 2.0, with several components supporting this way of distributing a computation (including eg tf.keras).

This issue investigates whether secure computations could be expressed as distribution strategies, thereby leveraging more of the built-in TF functionality.

**Comment by mortendahl** [comment]
@jvmancuso could you determine what the outcome is of this, not least the comments in https://github.com/tf-encrypted/tf-encrypted/pull/605, and potentially close this up before end of week?

**Comment by jvmancuso** [comment]
responded to your comments, will add an overview this week with my thoughts!
