### ISSUE TITLE
Fix bug in PySyft/TFE notebooks

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#539]
PRs:
- https://github.com/OpenMined/PySyft/pull/2247
- https://github.com/udacity/private-ai/pull/9

**Comment by mortendahl** [comment]
Only thing left is for OpenMined PR to be merged

**Comment by ianlivingstone** [comment]
@jvmancuso is going to reach out to pull this across the line

**Comment by mortendahl** [comment]
I should be able to get this one finished this week

**Comment by jvmancuso** [comment]
@mortendahl is this not ready to be merged? it was approved by Bobby and the last note here is that it was blocked by them merging it

**Comment by mortendahl** [comment]
Not yet, I had a quick chat with Andrew about what's missing

**Comment by mortendahl** [comment]
Done, waiting for review

**Comment by mortendahl** [comment]
Both PRs have been merged.
