### ISSUE TITLE
Different tensorflow protobuf formats

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#54]
There are a few different tensorflow protobuf formats. They are:

- GraphDef (https://www.tensorflow.org/extend/tool_developers/)
- MetaGraphDef (https://www.tensorflow.org/api_guides/python/meta_graph)
- SavedModel (https://www.tensorflow.org/guide/saved_model)

For importing we currently only support GraphDef which we're assuming it has the weights frozen directly in it. There are also cases where the GraphDef might have the weights stored in separate checkpoint files.

We need to investigate whether its better to support all three versions when converting a pre-trained model to and MPC graph or if supporting only GraphDef is sufficient.

My gut tells me we can get away with supporting only GraphDef for a while and once a MPC graph is built we can export that to a SavedModel for use with tensorflow serving (if we figure out that we can make use of tensorflow serving).

**Comment by justin1121** [comment]
Tensorflow is standardizing SavelModel with the release of TF 2.0. Might be a good time to start thinking about supporting SavedModel format!

**Comment by bendecoste** [comment]
+1 .. explains standardizing here: https://medium.com/tensorflow/whats-coming-in-tensorflow-2-0-d3663832e9b8?linkId=62351082

**Comment by bendecoste** [comment]
https://github.com/tensorflow/community/pull/34

**Comment by bendecoste** [comment]
One word of caution here is that custom models are just code, which ties further into #80
