### ISSUE TITLE
Update examples to use tfe.keras where possible

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#541]

**Comment by jvmancuso** [comment]
A bit more on this one:

We'd like to use the recently created tfe.keras.layers in place of the lower-level definitions we often find in the existing examples (e.g. `tfe.matmul(x, w) + b` can be replaced with a `Dense` layer from tfe.keras.layers).

**Comment by VMS-6511** [comment]
MNIST and SecureNN examples were implemented in open PR #578.
