### ISSUE TITLE
Keras example with plaintext training and private prediction

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#542]
### Context

As a user, it should be easy to train in plaintext a model with tf.keras then start serving private predictions with tfe.keras. We want to create an example demonstrating the process. 

### Next Steps
- [x] Add logic to convert a tf.keras model into a tfe.keras model #552
- [x] Create example in a notebook with user story

**Comment by yanndupis** [comment]
@mortendahl for this example, do you think we should use a serving queue and create a client which connects to the model with a query method? Basically same workflow as pysft?

**Comment by yanndupis** [comment]
Part of the PR #571, we have added a series of notebooks with a Secure Computation example: 

- [a - Secure Classification with TFE Keras - Public Training.ipynb](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/notebooks/a%20-%20Secure%20Classification%20with%20TFE%20Keras%20-%20Public%20Training.ipynb)
- [b - Secure Classification with TFE Keras - Secure Model Serving .ipynb](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/notebooks/b%20-%20Secure%20Classification%20with%20TFE%20Keras%20-%20Secure%20Model%20Serving%20.ipynb)
- [c - Secure Classification with TFE Keras - Private Prediction Client.ipynb](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/notebooks/c%20-%20Secure%20Classification%20with%20TFE%20Keras%20-%20Private%20Prediction%20Client.ipynb)

If we decide to create a high level api to wrap the player definition, model serving (`tfe.serving.QueueServer`) and model query (`tfe.serving.QueueClient`), we might want to revisit this example.
