### ISSUE TITLE
Converting a tf.keras model into a tfe.keras model

### ISSUE THREAD

**Issue by yanndupis** [tf-encrypted/tf-encrypted#552]
### Context

TFE now provides a tfe.keras api which matches tf.keras. Once a public tf.keras model is trained, we would like to be able to easily convert it into tfe.keras model.

**Comment by yanndupis** [comment]
@mortendahl, @jvmancuso - For the conversion, what do you guys prefer?

- A function which instantiates the tfe layers with the right parameters and load the weights:
```
tfe_model  = convert_to_tfe(keras_model, protocol)
```

or something like:
```
from tfe.keras.models import Sequential

model = Sequential()

with prot:
  model.from_config(keras_config)   # Create tfe model based on keras config

model.set_weights(keras_weights) . # Update weights based on keras weights
```

or something else?

**Comment by jvmancuso** [comment]
I like the latter, much more familiar and transparent for those coming from a pure Keras background  :)

**Comment by jvmancuso** [comment]
relevant: https://tf-encrypted.slack.com/archives/CJGFV71DF/p1560269776008100

**Comment by mortendahl** [comment]
Latter as well from me!
