### ISSUE TITLE
Decide if custom ops should continue to be optional

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#562]
Right now TFE will work without custom ops such as secure randomness, falling back to TensorFlow's insecure randomness. This means we can have some support on platforms that we do not publish official PyPI packages for, eg via source installations. Moreover, developers essentially only need to `git clone` to get started, and don't have to go through a bootstrapping step first. However, as we add more functionality or optimizations, it could become hard to maintain these alternatives. 

Options:

1. require custom ops to be present, making no attempts at falling back to alternatives; source code installations will still be possible but you will need a build environment

2. allow some functionality to simply be missing if the custom op is not there, causing an error if needed by the concrete application; this could eg be the case for protocols that heavily rely on custom ops such as HE.

3. continue to allowing different versions of functionalities, for instance falling back to a TensorFlow default if the custom op is missing; this could eg be the case for secure randomness

Note that in order to support third party MPC implementations we will in either case need some way of running with functionality missing, since these should *not* be bundled up in the main TFE pypi package (although potentially offered as extra pypi packages: `tf-encrypted-scalemamba` etc)

Child of #568

**Comment by mortendahl** [comment]
cc @ianlivingstone @justin1121 @jvmancuso -- wdyt about this?

**Comment by mortendahl** [comment]
One unknown is Windows, on which is it currently somewhat possible to run TFE yet we have no official support for. It is causing some issues though, and given that none of us currently runs Windows on a regular basis I'm cautious to add official support. See eg https://openmined.slack.com/archives/C6DEWA4FR/p1559899875021800

**Comment by justin1121** [comment]
I think I would prefer option 1.

> require custom ops to be present, making no attempts at falling back to alternatives; source code installations will still be possible but you will need a build environment

For developers the build time will be slower but we can make this automated and work in most cases but it will give the most obvious results and avoid problems developers might accidentally run into with the custom ops. If we were to go this route I think it would make sense to not allow it to work on windows at all until we have a proper testing/build system set up for it. (Perhaps this could be done before we actually drop any new custom ops forcing us to choose one way or another).

**Comment by gavinuhma** [comment]
I would think a combination of 2 and 3. Display a warning in the case of secure randomness falling back to an insecure default. It’s easier for local development that way, as long as you know it requires more install to be production ready.

**Comment by mortendahl** [comment]
> I think I would prefer option 1.

I like that there are less code paths, allowing us to have a better focus at the expense of sometimes having to say "not supported". Any thoughts on how we support third party libraries @justin1121?

**Comment by mortendahl** [comment]
> It’s easier for local development that way, as long as you know it requires more install to be production ready.

@gavinuhma yeah I like this aspect as well; hackers are more free to experiment. One mayor downside is the increase in code paths that we should test. For this reason I think I prefer 2 over 3. Downside is that availability of a functionality is binary, which means that you must be able to compile at least some customs ops (eg secure randomness).

**Comment by justin1121** [comment]
> I would think a combination of 2 and 3. Display a warning in the case of secure randomness falling back to an insecure default. It’s easier for local development that way, as long as you know it requires more install to be production ready.

This isn't just about secure randomness though. It's about all other custom operations we have in the future. I don't really agree this makes it easier for local development I think it makes it more confusing if you don't understand what's going on. The only thing that might be harder is waiting for the builds to complete which I don't think matters. Sensible defaults are more important to me than build times.

**Comment by justin1121** [comment]
> Any thoughts on how we support third party libraries @justin1121?

For development we just do what we do now. Pull down the libraries and build them and then link the final shared object.

For running we also continue what we do now and link in the static libraries from third party libs.

**Comment by mortendahl** [comment]
> For running we also continue what we do now and link in the static libraries from third party libs.

I'm not sure this is right solution given that we want to link to libraries such as SCALE-MAMBA and MP-SPDZ. I'm thinking that it would be better to ask the user to install these either manually or via other pip packages (say `tf-encrypted-scalemamba`). Moreover, some of these are under GPL ([GMP](https://gmplib.org/) for instance): https://www.apache.org/licenses/GPL-compatibility.html.

**Comment by justin1121** [comment]
> Moreover, some of these are under GPL (GMP for instance) and the issues that cause: https://www.apache.org/licenses/GPL-compatibility.html.

Forgot about licenses. Doesn't this mean we just can't use GMP? I don't think it matters whether its linked via a static or shared library.

**Comment by justin1121** [comment]
> I'm not sure this is right solution given that we want to link to libraries such as SCALE-MAMBA and MP-SPDZ.

Making a package for these might be a good idea. I'm not sure what inherently about these packages make it so we can't statically link against them though.

**Comment by justin1121** [comment]
Also GMP is dual licensed under LGPLv3 and GPLv2. Not sure what that means for us. Perhaps we need to dynamically link? Can't really find any solid information on it.

**Comment by ianlivingstone** [comment]
After some thought, I'd suggest:

- Focus on reducing complexity as much as possible (both for maintainers and users). 
- Our builds for each platform and operating system should contain a full suite of compiled operations -- I shouldn't have to do something extra to get the "base" working.
- A plugin system for more serious extensions makes sense which would require some sort of registration mechanism. Those plugins should conform to the previous point: they work out of the box for your platform and operating system to the best of our ability.
- Steer clear of duplicating functionality as much as possible -- which means having a clear line around what's included in the "base" by default and what is an extension.

With respect to licensing, if the license is copy-left, we should have those libraries outside of the primary repository with a clear warning regarding the underlying software. It's important that copy-left licenses don't end up inside the main package as it will be a barrier to company adoption.

**Comment by mortendahl** [comment]
> Our builds for each platform and operating system should contain a full suite of compiled operations -- I shouldn't have to do something extra to get the "base" working.

What do you mean by "our builds" here @ianlivingstone? The PyPI package? If so then I fully agree, for most people we'll always just be a `pip install tf-encrypted`!

> A plugin system for more serious extensions makes sense which would require some sort of registration mechanism.

To some extent TF is providing this already through the custom ops, and you can use python code to detect if a custom op is available or not. For custom ops I'm inclined to say that detection should *not* be used but we will simply fail if the op is not available (we can fail nicely by detecting that the op is not available, the point is just that there we provide no alternative). For protocols we might indeed want to use some kind of detection mechanism that eg allows us to pick the best protocol out of those available on the user's system. Maybe the distinction here is between what comes as part of TFE what comes in separate subpackages. The discussion in #568 is very relevant.

> With respect to licensing, if the license is copy-left, we should have those libraries outside of the primary repository with a clear warning regarding the underlying software. It's important that copy-left licenses don't end up inside the main package as it will be a barrier to company adoption.

Agreed!

**Comment by ianlivingstone** [comment]
> What do you mean by "our builds" here @ianlivingstone? The PyPI package? If so then I fully agree, for most people we'll always just be a pip install tf-encrypted!

Yep, that's exactly what I mean -- "build" being any artefact we publish for users to install.

> Maybe the distinction here is between what comes as part of TFE what comes in separate subpackages. The discussion in #568 is very relevant.

Agree -- this is the right distinction. I'm just advocating for a simple mechanism for loading the additional "requirements".

**Comment by mortendahl** [comment]
There is another option here, namely that TFE becomes free of protocols and they all move into sub-packages. This includes Pond and SecureNN. In this way TFE becomes somewhat more like Keras, and can likely stay free of custom-ops. It also puts all protocols on equal footing.

cc @jvmancuso @justin1121 @ianlivingstone

**Comment by ianlivingstone** [comment]
I'm a proponent of protocols being pluggable - it's a good long term architectural direction. In my mind, it's more of a question of when. I'd advocate for keeping it together until we understand the problem enough to draw the right abstractions.

**Comment by mortendahl** [comment]
The only symptom in https://github.com/tf-encrypted/tf-encrypted/issues/591 was a soft failure in the form of a warming. Because of this we have little knowledge about whether or how often this problem occurs. This might put us in favour of *not* allowing optional custom ops.

**Comment by mortendahl** [comment]
We're still experimenting with this in TF Big and TF Seal.

**Comment by mortendahl** [comment]
Believe we should *not* make custom ops optional:
- it seems better to focus on select platforms with tests than go wide without tests
- compiling on at least macOS and Ubuntu is somewhat straightforward, putting only a small burden on developers
- some of the optional fallbacks are not secure, ie randomness
- with TFE as an umbrella project it might interesting to provide a common set of functionalities, some of which will depend on custom ops
- we can still offer limited functionality on extra platforms, eg the ability to offer private inputs on [raspberry pis](https://www.piwheels.org/))

Will close this one down next week unless there are any objects

**Comment by mortendahl** [comment]
Closing this down with the conclusion that custom ops should *not* be optional. This will require a bit more of anyone who wishes to do a source installation.
