### ISSUE TITLE
Better error handling around loading custom ops

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#563]
Errors occur on Windows when loading custom ops (reported by @samratpyaraka):
- https://openmined.slack.com/archives/C6DEWA4FR/p1559899875021800
- https://openmined.slack.com/files/UK23GC3CH/FK536E8LB/image.png

It looks like the official TFE pypi package was installed, yet not sure how this is possible (any thoughts @justin1121?).

A simple solution might be to include platform information in the name of the object file, preventing it to be found on eg Windows if built on Unix (see eg https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/operations/secure_random/secure_random.py#L13)

We should also add better error handling if loading fails, support more exceptions or at least reporting any underlying error, see https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/operations/secure_random/secure_random.py#L18

Related: https://github.com/tf-encrypted/tf-encrypted/issues/513

Action items:
- [x] don't ship source package with object files, it will likely fail
- [x] better exception handling around loading

**Comment by justin1121** [comment]
Its still just doing a source install and for whatever reason the shared object is being included in the source tarball as well.

**Comment by justin1121** [comment]
> A simple solution might be to include platform information in the name of the object file, preventing it to be found on eg Windows if built on Unix

We can do this via the extension: .so for Unix, .dylib for MacOS and .dll for Windows.

**Comment by mortendahl** [comment]
> > A simple solution might be to include platform information in the name of the object file, preventing it to be found on eg Windows if built on Unix

> We can do this via the extension: .so for Unix, .dylib for MacOS and .dll for Windows.

If it problem is that the source package ships with object files then it might be better simply to strip these. Any logic we'd implement for checking the file extensions would essentially do what pip is already doing for us.
