### ISSUE TITLE
Directory structure around C++ code and custom ops

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#564]
Right now the implementation of custom ops lives in `/operations` and the linking python code in `/tf-encrypted/operations`. This doesn't seem to match neither https://github.com/tensorflow/tensorflow nor https://github.com/tensorflow/custom-op.

Knowing that we'll soon see more functionality written in C++ (eg HE) as well as more custom ops (for accessing external functionality and for optimizing protocols otherwise written in python) we should figure out which directory structure works best.

Related #568

**Comment by ianlivingstone** [comment]
Whichever directory structure we choose, we should ensure that we think through:

- Developer setup and maintenance
- The underlying build system and ensuring it's easy to understand, use, and maintain
- Having a cohesive strategy for testing the different components and how they interface together
- Clear documentation on how to add an additional operation
- Clear documentation on how all of this is built in CI and results in a published package

**Comment by mortendahl** [comment]
@justin1121 I'd love to hear your thoughts on this based on what you've seen elsewhere so far!

**Comment by justin1121** [comment]
I think it'd be great to match what tensorflow does for its ops and what they recommend for custom ops. 

```
├── tensorflow_time_two
│   ├── BUILD
│   ├── __init__.py
│   ├── cc
│   │   ├── kernels
│   │   │   ├── matmul.cu.cc
│   │   │   ├── matmul.h
│   │   │   ├── matmul_kernels.cc
│   │   │   ├── time_two.h
│   │   │   ├── time_two_kernels.cc
│   │   │   └── time_two_kernels.cu.cc
│   │   └── ops
│   │       ├── matmul_ops.cc
│   │       └── time_two_ops.cc
│   └── python
│       ├── __init__.py
│       └── ops
│           ├── __init__.py
│           ├── time_two_ops.py
│           └── time_two_ops_test.py
├── tensorflow_zero_out
│   ├── BUILD
│   ├── __init__.py
│   ├── cc
│   │   ├── kernels
│   │   │   └── zero_out_kernels.cc
│   │   └── ops
│   │       └── zero_out_ops.cc
│   └── python
│       ├── __init__.py
│       └── ops
│           ├── __init__.py
│           ├── zero_out_ops.py
│           └── zero_out_ops_test.py
```

So you have your high level op directory (`tensorflow_zero_out` above) then inside that your `cc` and `python` directories where the `cc` directory is split into the `kernels` directory (actual implementation of ops) and then a `ops` directory (where the  op is registered). 

One tricky thing is about where to put python code. If we're putting the custom op code inside of a different repo I think it makes sense to follow the above layout but if its going in the tf-encrypted repo then we may want to consider a slightly different layout. I think I'd want to get rid of the python directory and have the custom op code outside of the python package (`tf_encrypted`) and keep all the python code in that.

**Comment by mortendahl** [comment]
@justin1121 one thing I don't like about that structure is that it seems to spread code for eg a protocol implementation all over the place. Say most of SecureNN lives in `/tf-encrypted/protocol/securenn` but if we were to implement a few subparts in C++ then those would live in `/securenn/`?

**Comment by justin1121** [comment]
Yeah good point. We could have the C++ code inside the python package and strip it out when we package up the pip package. We might want to try rearchitecting the layout of secure random and see how it feels.

**Comment by mortendahl** [comment]
We're still experimenting with this in TF Big and TF Seal.

**Comment by mortendahl** [comment]
Closing this up. For now we've landed on https://github.com/tf-encrypted/tf-encrypted/issues/564#issuecomment-501713688 and https://github.com/tf-encrypted/tf-encrypted/issues/564#issuecomment-501733882
