### ISSUE TITLE
Decide if we want to switch to Travis CI

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#566]
Some issues seem to depend on us switching to Travis CI (see dependencies on this issue). Let us list pros and cons.

Options:

1. complete switch

2. partial switch

3. gradual switch

**Comment by justin1121** [comment]
Ideally all of our CI would run on same platform but if we were to implement a windows build then we could try out travis (since they are the only ones with windows support) and then gradually switch our other builds over to it. I think switching everything immediately will be too big of a task.

**Comment by ianlivingstone** [comment]
Which issues are dependent on switching and why?

**Comment by mortendahl** [comment]
> Which issues are dependent on switching and why?

See ZenHub dependencies

**Comment by justin1121** [comment]
Think we decided not to switch to travis ci. Circleci is launching windows support soon and getting windows support is not a high priority. If we want windows support sooner we can just implement something on travis ci for windows and don't have to switch any of the other builds.
