### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#567]
When we start to pull in more libraries we also have to deal with the licenses that these use. At the same time, consensus is that TFE should *not* fall back to eg GPL.

In this issue we should figure out how to best deal with using/linking external libraries given licensing constraints. This may have an impact on #568.

#### Background information

- [tldrlegal.com](https://tldrlegal.com): [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)), [MIT](https://tldrlegal.com/license/mit-license), [LGPL](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)), [GPL3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)), [AGPL](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0))
- [GNU recommends Apache 2.0 or LGPL](https://www.gnu.org/licenses/license-recommendations.html#libraries) yet [is pushing for GPL over LGPL](https://www.gnu.org/licenses/why-not-lgpl.html)

#### Relevant libraries

- [Sodium](https://github.com/jedisct1/libsodium): [ISC](https://en.wikipedia.org/wiki/ISC_license) (equivalent to MIT)
  - **bottom line**: both static and dynamic linking seem fine
- [GMP](https://gmplib.org/): [GNU LGPL v3 (or GNU GPL v2)](https://gmplib.org/)
  - **bottom line**: one of the following:
    - dynamically linked: TFE-GMP
    - statically linked sub-package: TFE-SubTFE-GMP, where SubTFE is LGPL
- [NTL](https://shoup.net/ntl/): [LGPL 2.1 or later, with notes](https://shoup.net/ntl/doc/copying.txt)
  - **bottom line**: one of the following:
    - dynamically linked: TFE-NTL
    - statically linked sub-package: TFE-SubTFE-NTL, where SubTFE is LGPL
- [SCALE-MAMBA](https://github.com/KULeuven-COSIC/SCALE-MAMBA): [Custom?](https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/master/License.txt)
  - **bottom line**: binary distribute is okay as long as copyright notice with attribution is included
- [MD-SPDZ](https://github.com/data61/MP-SPDZ):
  - [CSIRO Open Source Software Licence Agreement (variation of the BSD / MIT License)](https://github.com/data61/MP-SPDZ/blob/master/License.txt)
  - sublicense for [SPDZ-BMR-ORAM](https://github.com/mkskeller/SPDZ-BMR-ORAM): [Open Access Software Licence](https://github.com/mkskeller/SPDZ-BMR-ORAM/blob/master/License.txt) 
  - sublicense for [SPDZ-2](https://github.com/bristolcrypto/SPDZ-2/): [Open Access Software Licence](https://github.com/bristolcrypto/SPDZ-2/blob/master/License.txt)
  - **bottom line**: binary distribute is okay as long as copyright notice with attribution is included
- [ABY](https://github.com/encryptogroup/ABY): [AGPL](https://github.com/encryptogroup/ABY/blob/public/LICENSE)
  - **bottom line**: don't see this happening
- [TFHE](https://github.com/tfhe/tfhe): [Apache 2.0](https://github.com/tfhe/tfhe/blob/master/LICENSE)
  - **bottom line**: both static and dynamic linking seem fine
- [SEAL](https://github.com/microsoft/SEAL): [MIT](https://github.com/microsoft/SEAL/blob/master/LICENSE)
  - **bottom line**: both static and dynamic linking seem fine
- [HElib](https://github.com/homenc/HElib): [Apache 2.0](https://github.com/homenc/HElib/blob/master/LICENSE)
  - **bottom line**: both static and dynamic linking seem fine
- [HEAAN](https://github.com/kimandrik/HEAAN): [CC-NonCommercial Unported](https://creativecommons.org/licenses/by-nc/3.0/)
  - **bottom line**: not sure how we'd deal with the non-commercial aspects
- [PALISADE](https://git.njit.edu/palisade/PALISADE): [Custom?](https://git.njit.edu/palisade/PALISADE/blob/master/License.md) must include copyright notice
  - **bottom line**: both static and dynamic linking seem fine

#### MIT/Apache libraries:

Don't see any problems here.

#### [LGPL](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)) libraries:

> Derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, but applications that use the library don't have to be.

> The choice of license makes a big difference: using the Lesser GPL permits use of the library in proprietary programs; using the ordinary GPL for a library makes it available only for free programs.

From [here](https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic)

> (1) If you statically link against an LGPLed library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.
>
> (2) If you dynamically link against an LGPLed library already present on the user's computer, you need not convey the library's source. On the other hand, if you yourself convey the executable LGPLed library along with your application, whether linked with statically or dynamically, you must also convey the library's sources, in one of the ways for which the LGPL provides. 

We should not statically link to these libraries, must load them dynamically

#### [GPL](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) and [AGPL](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) libraries:

> Any modifications to or software including GPL-licensed code must also be made available under the GPL along with build & install instructions.

Don't see this happening in any form; GPL seems to spill in even if we only use them through subpackages

**Comment by ianlivingstone** [comment]
> don't see this happening in any form; GPL seems to spill in even if we only use them through subpackages

This could be a user choice -- if architected properly the subpackage can consume tf-encrypted and register itself as making new options available. In this sense, tf-encrypted itself would not take on anything GPL related.

**Comment by mortendahl** [comment]
Good point! I've been thinking more from the point of view of what TFE consumes than what consumes TFE. For the latter Apache 2.0 still seems like a good choice to me (see eg https://www.apache.org/licenses/GPL-compatibility.html), any thoughts?

**Comment by ianlivingstone** [comment]
> For the latter Apache 2.0 still seems like a good choice to me (see eg https://www.apache.org/licenses/GPL-compatibility.html), any thoughts?

Agreed :)

**Comment by mortendahl** [comment]
Added bottom lines to all relevant libraries. Closing for now.
