### ISSUE TITLE
Decide on strategy for external libraries and frameworks

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#568]
We want to have a strategy for using external libraries and bridging external frameworks such as:
- [GMP](https://gmplib.org/), [NTL](https://shoup.net/ntl/)
- [SCALE-MAMBA](https://github.com/KULeuven-COSIC/SCALE-MAMBA), [MD-SPDZ](https://github.com/data61/MP-SPDZ), [ABY](https://github.com/encryptogroup/ABY), [TFHE](https://github.com/tfhe/tfhe), [SEAL](https://github.com/microsoft/SEAL), [HEAAN](https://github.com/kimandrik/HEAAN), [PALISADE](https://git.njit.edu/palisade/PALISADE), [cude-fixnum](https://github.com/data61/cuda-fixnum/)

The main question is where this code should live, which has several aspects:

- **bloat**: some functionality is more experimental and should probably not be included by default, both for the sake of size but also to keep the number of hard dependencies down

- **licensing**: some code might conflict with our Apache 2.0 license

- **usability**: getting TFE running should be as easy as possible, ideally even on platforms we are not officially supporting

- **ease of development**: contributing code etc to TFE should be easy, including getting set up with a reasonable development environment

- **responsibility**: flexibility in allowing non-core TFE contributors to maintain bridges; could for example be the core maintainer of the framework

Desired outcomes of this issues:
- [ ] decision on strategy
- [ ] example bridge (eg #418)
- [ ] template project for bridging external frameworks into TFE (including instructions etc)

**Comment by justin1121** [comment]
We could move this https://github.com/tf-encrypted/tf-encrypted/pull/560 to a different repo to build a first project for bridging external libs.

**Comment by mortendahl** [comment]
Based on findings in #567 it seems that we should only dynamically link against eg GMP and NTL, ie the installation process would have to make sure that these are installed on the user's system.

While this is doable, I also like the idea of not having these as hard dependencies of TFE, since they may not be easily available on all devices that we want to play around with (although they are not main target for TFE, I've previously had issues with GMP on RPis and phones).

To me this suggests a structure where code that has a hard dependency on dynamically linked libraries should live in subpackages and not in the main TFE package.

**Comment by mortendahl** [comment]
I think I like the idea of having bridges in separate repos and PyPI packages, say `github.com/tf-encrypted/bridge-scale-mamba` and `tf-encrypted-scalemamba`. Benefits:
- keeps the core clean and easy to get started on with few dependencies (roughly only TF)
- avoids licensing issues by only linking dynamically
- keeps frameworks optional in an obvious manner
- allows non-core members to keep the bridge close to the framework if they desire (say on their GitHub account)

**Comment by mortendahl** [comment]
To close this one up, from #567 it seems that we either have to:
1. be okay with dynamically linking libraries (especially GMP/NTL) 
2. move to sub-packages (which are dynamically linked with TFE but can themselves be statically linked to GMP/NTL as long as they are under LGPL).

For 1. to be a real options we have to ensure at least three things:
- that pip allows us to easily ensure that they are installed
- that they are readily available on all target platforms in binary form (homebrew has them for macOS, APT has them for Debian/Ubuntu, less clear on Windows)
- that the above doesn't make any real assumptions about the user's environment ("install GMP through homebrew...") or require additional installations ("download xcode, setup development environment, ...")

I haven't found a solution that satisfies all three points, not least since packages such as `gmpy` and `gmpy2` [only seem to provide wrappers](https://github.com/aleaxit/gmpy/issues/128). For this reason I think moving to dynamically linked sub-packages seems like the right move forward.

Closing the issue; happy to reopen if there is more to be said.
