### ISSUE TITLE
Wrong results on Windows

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#577]
The following script produces correct results on macOS+Linux but fails on Windows:

```python
import tensorflow as tf
import tf_encrypted as tfe

x = tfe.define_private_variable(tf.constant([1,2,3,4], shape=[2,2]))
y = tfe.matmul(x, x)
z = y.reveal()

sess = tfe.Session()
sess.run(tf.global_variables_initializer())
sess.run(z)
```

On macOS the output is
```
array([[ 7., 10.],
       [15., 22.]])
```

while on Windows it is:
```
array([[-2.48975022e+14, -2.48975022e+14],
       [-2.48975022e+14, -2.48975022e+14]])
```

I've tried both with and without secure random on macOS, both give correct results.

**Comment by mortendahl** [comment]
Even simpler things fail as well:

```python
import tensorflow as tf
import tf_encrypted as tfe

x = tfe.define_private_variable(tf.constant([1,2,3,4], shape=[2,2]))
y = x * 1
z = y.reveal()

sess = tfe.Session()
sess.run(tf.global_variables_initializer())
sess.run(z)
```

**Comment by ianlivingstone** [comment]
@mortendahl is going to investigate this bug and decide on windows support based on how difficult it is to resolve this bug.

**Comment by mortendahl** [comment]
[Different int size](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine) messing [`_encode`](https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/protocol/pond/pond.py#L725) is best guess at a culprit at this point:

```python
np.array([617673396283947]).astype(int)
```

returns `617673396283947` on macOS but `1264544299 = 617673396283947 % 2**32` on Windows.

Will patch this and see if it's enough to solve the problem.

**Comment by mortendahl** [comment]
Issue resolved on main branches of TFE and PySyft.
