### ISSUE TITLE
dilation_rate not implemented error in keras conv2D

### ISSUE THREAD

**Issue by avitalsh** [tf-encrypted/tf-encrypted#582]
Hi, 
I was trying to use the new tf.keras to tfe.keras conversion (PR #571 ) using the following code - 
```
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(filters=16, kernel_size=(3,3), use_bias=False))

model.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])

config = tfe.LocalConfig()
tfe.set_config(config)
tfe.set_protocol(tfe.protocol.SecureNN())

tf.reset_default_graph()

with tfe.protocol.SecureNN():
    tfe_model = tfe.keras.models.clone_model(model)
```

```tf.keras.layers.Conv2D``` has a default ```dilation_rate``` value (1,1). While building the tfe.keras model we reach this if statement:
https://github.com/tf-encrypted/tf-encrypted/blob/0c4aa9b5a2a16b44e4d595e73b72c11d02a90140/tf_encrypted/keras/layers/convolutional.py#L122-L125
Which makes us crush with the following error - 
NotImplementedError: `dilation_rate` argument is not implemented for layer Conv2d
 
I tried setting ```dilation_rate```  to None as a quick workaround but it raised a value error because ```dilation_rate``` should be: 

>  an integer or tuple/list of 2 integers

**Comment by yanndupis** [comment]
Hi @avitalsh, thank you very much for raising this issue. I see the problem. I will fit it today.
