### ISSUE TITLE
Spice up the README with new logo and colours

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#607]

**Comment by mortendahl** [comment]
cc @gavinuhma

**Comment by jvmancuso** [comment]
"Spicy up" ftw 💯

**Comment by gavinuhma** [comment]
@mortendahl ok if I create a `docs` label for this?

**Comment by gavinuhma** [comment]
Discussed with Morten offline. We're attaching this to #537

**Comment by gavinuhma** [comment]
I believe this is done. Closing
