### ISSUE TITLE
About the function which named "_add_private_private" in pond.py. 

### ISSUE THREAD

**Issue by zhq0918** [tf-encrypted/tf-encrypted#628]
I tested the example which named federated-learning, and it reported the error information as flows:
File "..\Python35\lib\site-packages\tf_encrypted\protocol\pond\pond.py", line 2511, in _add_private_private
    with **tf.device(prot.server_0.device_name):**AttributeError: 'NoneType' object has no attribute 'device_name'. 
I traced the code, and i find the function which named **_add_private_private** in pond.py, the object prot attribute **server_0** and **server_1** were all none, why? how can i resolve the problem? thanks.

**Comment by mortendahl** [comment]
Hi @zhq0918, thanks for reporting this! Could you tell us which version of TF Encrypted you're using? From the filename I'm assuming you're on Windows?

**Comment by zhq0918** [comment]
Hi @mortendahl ,thank your response. The tf-encrypted that i downloaded is tf-encrypted-master.I have tested it   in windows and ubuntu 16.04, All report the same error. The error information in ubuntu16.04 as flows:
  File "examples/federated-learning/run.py", line 188, in <module>
    for grads in model_grads
  File "examples/federated-learning/run.py", line 188, in <listcomp>
    for grads in model_grads
  File "/opt/tf-encrypted/tf_encrypted/protocol/protocol.py", line 89, in cache_nodes
    result = func(self, *args, **kwargs)
  File "/opt/tf-encrypted/tf_encrypted/protocol/pond/pond.py", line 893, in add_n
    return reduce(lambda x, y: x + y, tensors)
  File "/opt/tf-encrypted/tf_encrypted/protocol/pond/pond.py", line 893, in <lambda>
    return reduce(lambda x, y: x + y, tensors)
  File "/opt/tf-encrypted/tf_encrypted/protocol/pond/pond.py", line 1593, in __add__
    return self.prot.add(self, other)
  File "/opt/tf-encrypted/tf_encrypted/protocol/protocol.py", line 89, in cache_nodes
    result = func(self, *args, **kwargs)
  File "/opt/tf-encrypted/tf_encrypted/protocol/pond/pond.py", line 828, in add
    return self.dispatch("add", x, y)
  File "/opt/tf-encrypted/tf_encrypted/protocol/pond/pond.py", line 1373, in dispatch
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/opt/tf-encrypted/tf_encrypted/protocol/pond/pond.py", line 2511, in _add_private_private
    with tf.device(prot.server_0.device_name):
AttributeError: 'NoneType' object has no attribute 'device_name'
best regards
zhq0918

**Comment by mortendahl** [comment]
I'm having trouble reproducing on my side. Did you make any changes to the script before running it?

**Comment by zhq0918** [comment]
The step that i operated:
1、I added the config.json，the config json file as flows:
{
        "model-owner": "10.130.179.X:4440",
        "data-owner-0": "10.113.215.X:4440",
        "data-owner-1": "10.113.215.X:4440",
        "data-owner-2": "10.113.214.X:4440"
}
2、In the corresponding machine, i run the scripts as flows:
python3 -m tf_encrypted.player model-owner --config config.json
python3 -m tf_encrypted.player data-owner-0 --config config.json
python3 -m tf_encrypted.player data-owner-1 --config config.json
python3 -m tf_encrypted.player data-owner-2 --config config.json
3、Finally， i ran the script as flows: 
python3 examples/federated-learning/run.py config.json

**Comment by mortendahl** [comment]
Oh that explains it, thanks! You need to have entries and launch players for the compute servers as well. Something like:
```
{
"model-owner": "10.130.179.X:4440",
"data-owner-0": "10.113.215.X:4440",
"data-owner-1": "10.113.215.X:4440",
"data-owner-2": "10.113.214.X:4440",
"server0": "<ip>",
"server1": "<ip>",
"server2": "<ip>",
}
```

You can use the data owners as the compute servers as well so you don't need more instances. In that case you need to explicitly create a protocol and pass the player names to it; let me know if you want to do this and I'll be happy to help.

https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/notebooks/serving/Server.ipynb provides some hints in any case!

**Comment by zhq0918** [comment]
thanks,i'll try it again.

**Comment by zhq0918** [comment]
Hi,@mortendahl, i have tried it, and now my config as flows:
{
        "model-owner": "10.130.179.159:4440",
        "data-owner-0": "10.113.215.153:4440",
        "data-owner-1": "10.113.215.154:4440",
        "data-owner-2": "10.113.214.189:4440",
        "server0": "10.113.215.153:4441",
        "server1": "10.113.215.154:4441",
        "server2": "10.113.214.189:4441"
}
but  i met problem in the model-owner,here‘s the information:
2019-07-24 08:22:30.697859: I tensorflow/core/distributed_runtime/master.cc:268] CreateSess
ion still waiting for response from worker: /job:tfe/replica:0/task:4
2019-07-24 08:22:30.697859: I tensorflow/core/distributed_runtime/master.cc:268] CreateSess
ion still waiting for response from worker: /job:tfe/replica:0/task:5
2019-07-24 08:22:30.697859: I tensorflow/core/distributed_runtime/master.cc:268] CreateSess
ion still waiting for response from worker: /job:tfe/replica:0/task:6
why? how can i resovle this problem? and if this program is executed, how long will it last?thanks.

best regards
zhq0918

**Comment by mortendahl** [comment]
Hi @zhq0918, is the problem that it hangs?

The `X` in the IP address of the target `grpc://10.130.179.X:4440` looks strange; not sure if that's what you're seeing or not?

**Comment by zhq0918** [comment]
Hi @mortendahl ,thank your response. I have tried again in the same machine which ip was 10.113.214.189,and it was ok. but the 10.113.215.154 was not ok, I don't think the machine with IP 10.113.215.154 is properly configured. i will try again in the machine whic ip is 10.113.215.154 .

**Comment by mortendahl** [comment]
Happy you got it working! Feel free to reopen this issue or file another as needed.

**Comment by zhq0918** [comment]
@mortendahl .Thank you very much.
