### ISSUE TITLE
How to add two tensor in tfe?

### ISSUE THREAD

**Issue by thormacy** [tf-encrypted/tf-encrypted#632]
I am trying to implement a federated learning model. Not sure does tf-encrypted support directly add two tensor using HE? Trying to use add(x,y), but it has somehow some problems with lift function.

**Comment by thormacy** [comment]
The error is: Don't know how to lift <class 'tensorflow.python.framework.ops.Tensor'>, <class 'tensorflow.python.framework.ops.Tensor'>

**Comment by thormacy** [comment]
BTW when I trace the source code, what is pondtensor?  Seems x,y should be only three types int, float or PondTensor

**Comment by mortendahl** [comment]
Hey @thormacy, do you have any code you can share? It looks like you are trying to add to TensorFlow tensors together using TF Encrypted.

We currently only have support for secure multi-party computation, with homomorphic encryption coming next.

**Comment by thormacy** [comment]
Hi mortendahl, a simply example is as followed:
```
import tensorflow as tf
import tf_encrypted as tfe


# define inputs 
x = tf.ones(shape=(5, 10))
w = tf.ones(shape=(5, 10))

# define computation
y = tfe.add(x, w)

with tfe.Session() as sess:
    # initialize variables
    sess.run(tfe.global_variables_initializer())
    # reveal result
    result = sess.run(y.reveal())
```
In the original code, I am also using tf.feature_column, so I can't directly use tfe.

**Comment by jvmancuso** [comment]
Hi @thormacy, I believe the problem is that `x` and `w` need to be created through our tfe.local_computation decorator.  A good example can be found in the [README](https://github.com/tf-encrypted/tf-encrypted#usage). I've modified your example with the proper adjustments:

```python
import tensorflow as tf
import tf_encrypted as tfe

@tfe.local_computation
def provide_input():
    return tf.ones(shape=(5, 10))

# define inputs 
x = provide_input(player_name='input-provider-0')
w = provide_input(player_name='input-provider-1')

# define computation
y = tfe.add(x, w)

with tfe.Session() as sess:
    # initialize variables
    sess.run(tfe.global_variables_initializer())
    # reveal result
    result = sess.run(y.reveal())
```

Notice that the key difference is that we have to annotate the creation of inputs to tfe operations with a `player_name`, largely because multi-party computation requires distinct parties or "players" who want to keep their inputs private.

**Comment by mortendahl** [comment]
Hi @thormacy, did this answer your question? Happy to reopen the issue if not!

**Comment by thormacy** [comment]
Hi mortendahl, thanks for the help. It works.

**Comment by sidharthramesh** [comment]
I am using tfencrypted to do addition of some secret numbers in a network. The secret numbers are dynamically generated and are different on each node.
```python
def provide_input() -> tf.Tensor:
  with open("/tmp/result.txt") as f:
      result = int(f.read())
      print(result)
  return tf.ones(shape=(1,)) * result

inputs = [
      tfe.define_private_input('server0', provide_input),
      tfe.define_private_input('server1', provide_input),
      tfe.define_private_input('server2', provide_input)
  ]
```
My config.json is (I am running it in a docker network with the workers as services)
```
{
    "server0": "worker1:4440",
    "server1": "worker2:4440",
    "server2": "worker3:4440",
}
```
I am currently storing the results /tmp/results.txt, but even so, only the result on the computer running the script gets returned (If I'm running on server0, the result.txt from server0). I want the input to be different for different computers on the network. How do I do that? Is there an easier/more straight forward way to achieve this?

Thank you

**Comment by sidharthramesh** [comment]
Oh, I guess my question is the same as https://github.com/tf-encrypted/tf-encrypted/issues/490. I will look into local data. However, the documentation could mention about this in the Federated Averaging example.
