### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by thormacy** [tf-encrypted/tf-encrypted#633]
When I try the example on readme:
```
import tensorflow as tf
import tf_encrypted as tfe

@tfe.local_computation('input-provider')
def provide_input():
    # normal TensorFlow operations can be run locally
    # as part of defining a private input, in this
    # case on the machine of the input provider
    return tf.ones(shape=(5, 10))

# define inputs
w = tfe.define_private_variable(tf.ones(shape=(10,10)))
x = provide_input()

# define computation
y = tfe.matmul(x, w)

with tfe.Session() as sess:
    # initialize variables
    sess.run(tfe.global_variables_initializer())
    # reveal result
    result = sess.run(y.reveal())
```

Found attached error:
`AttributeError: module 'tf_encrypted' has no attribute 'local_computation'
`
I installed tf_encrypted by pip3

**Comment by mortendahl** [comment]
Hi @thormacy, which version of TF Encrypted are you using (`pip list | grep tf-encrypted`)? The `local_computation` decorator was only introduced in the latest release (0.5.7).

**Comment by thormacy** [comment]
ok. I see. My tf-encrypted version is (0.5.6)

**Comment by mortendahl** [comment]
A `pip install -U tf-encrypted` should help then! Let us know if it doesn't and we'll reopen this issue. Thanks for giving TF Encrypted a try! 🙌

**Comment by xahmadzai** [comment]
when i try to import "import tf_encrypted as tfe" it give me the following error, could anyone help me please

AttributeError: module 'tensorflow' has no attribute 'Session'

i also tried to use "tf.compat.v1.disable_eager_execution()" but it also doesn't work

**Comment by paspularavinder** [comment]
when I try to import "import tf_encrypted as tfe" it give me the following error, could anyone help me please

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

i also tried to use "tf.compat.v1.disable_eager_execution()" but it also doesn't work
