### ISSUE TITLE
Failure of div function

### ISSUE THREAD

**Issue by execl** [tf-encrypted/tf-encrypted#667]
The div function in Pond protocol supports a public divisor y. The protocol handles y as calculate its inverse (1 / y.decode()) and multiple it with the dividend x. However this inverse is a tensor (after decode) and is incompatible with the lift function in mul. 
An error occurs:
 TypeError: Don't know how to lift <class 'tf_encrypted.protocol.pond.pond.PondPrivateVariable'>, <class 'tensorflow.python.framework.ops.Tensor'>

**Comment by mortendahl** [comment]
One fix would be to implement and use [`tf.reciprocal`](https://www.tensorflow.org/api_docs/python/tf/math/reciprocal) for public tensors (eg decode, compute native reciprocal, encode).

In the particular case reported here this will result in a multiplication between a private variable and a public tensor, which will be properly handled by `lift` and in turn `mul`.
