### ISSUE TITLE
Integrate with TensorFlow 2.0

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#679]
In [this](https://github.com/tf-encrypted/tf-encrypted/pull/678) PR I've started getting the tf 2.0 transition ready. Currently the tests are passing in the PR but its still using the 1.X API. In `conftest.py` its disabling the v2 behavior with `tf.compat.v1.disable_v2_behavior()`. As tests are moved over to the tf 2.0 we enable v2 behavior for those individual tests.

Doing this conversion and this [doc](https://www.tensorflow.org/beta/guide/migration_guide#make_the_code_20-native) from Tensorflow has given a good feel for what the major changes are going to be.

One interesting decision we need to make is whether we want to continue to be master compatible with the tf 2.0 changes (meaning master will continue to work with both tf 1.14 and tf 2.0 pip packages) or if we want to have a longer running branch where we put all the 2.0 changes into. I'm pretty open to either direction but think keeping tf 1.14 working will become more complicated as we convert more and more code to use tf 2.0 API.

**Major Changes**

I believe these can be completed independently for the most part.

In no particular order:

- [ ] Convert tests to use `tf.function` instead of `tf.Session`
- [ ] Figure out best way to configure devices etc like we do with `tfe.Session` without subclassing `tf.Session` especially for `RemoteConfig`.
- [ ] Figure out best way to enable eager execution. Thinking it might work to create something like a `EagerConfig` in the spirit `LocalConfig` and `RemoteConfig`
- [ ] Start converting any leftover uses of `tf.compat.v1.*`.
- [ ] Update any tfe API to match the corresponding v2 API in Tensorflow
- [ ] Update the converter to work with v2 API
- [ ] During the above conversion I noticed some oddities with the `space_to_batch`/`batch_to_space` API. Figure out this.
- [ ] Variables work quite a bit different with `tf.function` figure out how we can make this work

**Comment by mortendahl** [comment]
> Thinking it might work to create something like a EagerConfig in the spirit LocalConfig and RemoteConfig

This seems to be orthogonal things to me, ie all combinations makes sense: (eager, local), (eager, remote), (non-eager, local), (non-eager, remote).

**Comment by mortendahl** [comment]
We need to do a thorough review as well to make sure we understand what's happening and that it doesn't break security anywhere.

**Comment by yanndupis** [comment]
Hey @justin1121, with your recent work on TF2.0, how does the API look like now if we want to add two private tensors? Does it look like this?

```
@tf.function
with tfe.protocol.SecureNN() as prot
   x_in = np.array([1, 2, 3, 4])
   y_in = np.array([5, 6, 7, 8])
   x_p = prot.define_private_tensor(x_in)
   y_p = prot.define_private_tensor(y_in)
   
   res_p = tfe.add(x_p, y_p)
   print("public result", res_p.reveal())
```

**Comment by justin1121** [comment]
Close!

```
from tf_encrypted.utils import unwrap_fetches

@tf.function
def func():
  with tfe.protocol.SecureNN() as prot
     x_in = np.array([1, 2, 3, 4])
     y_in = np.array([5, 6, 7, 8])
     x_p = prot.define_private_tensor(x_in)
     y_p = prot.define_private_tensor(y_in)
   
     res_p = tfe.add(x_p, y_p)

     return unwrap_fetches(res_p.reveal())
print("public result", func())
```

`unwrap_fetches` is needed until we find a good way to wrap `tf.function`, currently `tfe.Session` is called `unwrap_fetches` for us.

**Comment by yanndupis** [comment]
Gotcha, thanks! that's helpful. what would be the equival in plaintext TF2.0?
```
@tf.function
def func():
  
   x = tf.constant([1, 2, 3, 4])
   y = tf.constant([5, 6, 7, 8])
   
   res = tf.add(x, y)

   return res

print("Result", func())
```

**Comment by justin1121** [comment]
you got it.

**Comment by mortendahl** [comment]
There might be a better way using eg tf.Graph.as_default_graph

**Comment by justin1121** [comment]
If `tf.function` works the way we expect it too I think it would be best encourage use of that because that is what users would expect when using tf 2.0 (although maybe they just expect eager computations). `tf.Graph.as_default_graph` may be especially useful for converting public graphs to private graphs though. Overall, supporting both might be ideal although I can't find an obvious way to to run a graph once you've created it (it must exist somewhere though).

**Comment by mortendahl** [comment]
I think you're right @justin1121, `tf.function` seems like the best approach. One thing I don't like is that we're leaking implementation details by doing it that way. I suggest introducing a `tfe.encrypted_computation` decorator instead, along the lines of what TF Federated is doing. For now this decorator might simply forward everything to `tf.function`.

**Comment by justin1121** [comment]
> One thing I don't like is that we're leaking implementation details by doing it that way. I suggest introducing a tfe.encrypted_computation decorator instead, along the lines of what TF Federated is doing. For now this decorator might simply forward everything to tf.function.

I'll look into this a bit. Wasn't sure exactly how this would work at first but now I have some ideas.

I've just started digging into the examples a bit which are more likely to be more nuanced around how they work compared to how some of the tests work which should give us some more idea around what we need to fix (e.g. what needs to be done for `tfe.local_computation`).

**Comment by mortendahl** [comment]
> what needs to be done for `tfe.local_computation`

I've started an RFC for the larger design, but down the line I'm imagining `tfe.local_computation`s to map between zero or more `LocalTensor`s, which are essentially just a wrapper type around a pinned TensorFlow tensor carrying a bit of extra metadata such as placement. `tfe.local_computation` will perform a type check to eg make sure its own placement match that of inputs and outputs.

The decorated functions should be usable both in graph and eager mode; the former as they may form a part of a larger graph computation, and the latter to enable eg debugging. While the wrapping type might prevent `tfe.local_computation` to be a direct derivative of `tf.function`, I could easily see it being used by it internally, perhaps in-between unwrapping and rewrapping.

This is somewhat similar to `tff.tf_computation` in TF Federated.

**Comment by skeydan** [comment]
Hi there,

hope I'm not misusing this issue too much with my question :-)
I am wondering what is the TFE roadmap for supporting TF 2 - or does it already?

(Concretely, I am interested in combining TFE with PySyft, and am using their Udacity package bundle for experimentation, and there the TF version is 1.15.)

Many thanks!!

**Comment by jvmncs** [comment]
hi @skeydan, sorry that we overlooked your question before :(

I've written an update about tf 2.x support in [this comment](https://github.com/tf-encrypted/tf-encrypted/issues/799#issuecomment-636127262). thanks for your interest, we enjoyed your blog post!

**Comment by skeydan** [comment]
Thanks @jvmncs for the update, and very happy to hear you liked the post! :-)

**Comment by vincehong** [comment]
TFE 0.9.0 now supports TF2.
