### ISSUE TITLE
Migrate tests to use tf.function instead of tfe.Session

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#680]
One of the best ways we can detect whether we'll run into trouble with tf 2.0 API is by converting the tests to use `tf.function` instead of `tfe.Session`. 

Couple issues already discovered that we can make quick workarounds for now:

1. Functions/methods wrapped by `tf.function` must return a `tf.Tensor`. This isn't that different from how `tf.Session` works but we created a subclass of that called `tfe.Session` that unwraps the tfe types for us. As a first step I think we should just call the `unwrap_fetches` function manually in the tests and in the future we can think about creating our own `tfe.function` that handles the unwrapping for us.

2. Variables work in quite a different way with `tf.function` and we're using variables unnecessarily in a lot of tests. I think we need to be a little more thoughtful about how we're using variables and move away from using them in tests unless needed (e.g. keras training tests).

**Comment by mortendahl** [comment]
Closing in favour of [this strategy](https://github.com/tf-encrypted/tf-encrypted/pull/795)
