### ISSUE TITLE
Removing support for TensorFlow 1.X

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#683]
We are considering removing TensorFlow 1.X support because TF 2.0 will be landing soon and this is the future of TensorFlow. TF-Encrypted 0.5.9 will be the last release with TF 1.X support.

**Comment by justin1121** [comment]
Feedback welcome from any users that might need to rely on TensorFlow 1.X!

**Comment by matthew-mcateer** [comment]
No objections here. I'm in favor of making TF 2.0 the default from now on, as long as me make this known in the installation instructions.

**Comment by mortendahl** [comment]
This should be done as part of landing TF2 support in master.

**Comment by mortendahl** [comment]
Closing with the conclusion of dropping support for TF1 as part of migrating to TF2.
