### ISSUE TITLE
More friendly way to reset the graph

### ISSUE THREAD

**Issue by zicofish** [tf-encrypted/tf-encrypted#688]
In the current version, whenever a user tries to reset the graph (sometimes necessary due to large memory consumption), he needs to first clear the initializers manually:

```
import tensorflow as tf
import tf_encrypted as tfe

# Imagine this is a large graph, although I only define a single variable node
a = tfe.define_private_variable(tf.ones(shape=(1,1)))

with tfe.Session() as sess:
    sess.run(tfe.global_variables_initializer())
    result = sess.run(a.reveal())
    print(result)

tfe.clear_initializers()  # THIS IS NOT SO NICE
tf.reset_default_graph()

# Imagine this is another large graph, although I only define a single variable node
b = tfe.define_private_variable(tf.ones(shape=(1,1)))
with tfe.Session() as sess:
    sess.run(tfe.global_variables_initializer())
    result = sess.run(b.reveal())
    print(result)
```

Without `tfe.clear_initializers()`, the script will throw error. Only users who are reasonably familiar with the library would know to call this function first...

Why not having a `tfe.reset_default_graph()` where we put this call inside? This might not be a best solution because users might still call `tf.reset_default_graph()` instead of `tfe.reset_default_graph()`.

**Comment by mortendahl** [comment]
Fully agree @acs6610987, switching graphs and protocols is currently a bit of a mess.

We've been putting a fix for this off for a while, but current plan is to solve this during the ongoing TF2 refactoring. This should get rid of most, if not all, global state, and in turn eliminate the issue.

I also imagine that the notion of a graph goes away, instead using abstractions such as e.g.:

```python
client = tfe.Player()
server0 = tfe.Player()
server1 = tfe.Player()

pond = tfe.protocols.Pond(server0, server1, ...)

@tfe.encrypted_computation(protocol=pond)
def forward(x):
  w = tf.Tensor(...)
  y = tfe.matmul(x, w)
  return y

@tfe.plaintext_computation(protocol=pond, player=client)
def provide_input():
  x = tf.Tensor(...)
  return x

@tfe.plaintext_computation(protocol=pond, player=client)
def receive_output(y):
  tf.print(y)

x = provide_input()  # additive secret shared value
y = forward(x)  # additive secret shared value
receive_output(y)
```

**Comment by mortendahl** [comment]
Due to https://github.com/tf-encrypted/tf-encrypted/pull/755, I believe that this will be solved with https://github.com/tf-encrypted/tf-encrypted/issues/761.

**Comment by zjn-code** [comment]
In TFE based on TF2, there is no need to reset the graph.
