### ISSUE TITLE
Convert TF Keras into TFE Keras

### ISSUE THREAD

**Issue by Xusita** [tf-encrypted/tf-encrypted#693]
I try to follow the example code, but every time when I try to use tfe.keras.models.clone_model(model) to convert tf keras into tfe keras, the Python is blocked and even change computer doesn't work.

**Comment by mortendahl** [comment]
Hi @Xusita, which version of TF Encrypted are you using? By blocked you mean it keeps running forever?

**Comment by Xusita** [comment]
@mortendahl Hey, thx for your reply! Yes, the computer seems to run forever.
the TFE version I use is 0.5.9, and TF version is 1.13.1.

**Comment by yanndupis** [comment]
hey @Xusita,

Are you experiencing this problem when running [this following notebook](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/notebooks/keras-classification/b%20-%20Secure%20Model%20Serving.ipynb)? if yes, did you launch the server as described in the 
`Launching servers` section?

**Comment by Xusita** [comment]
@yanndupis Hey, I think I do launch the server as follow:

`for player_name in players.keys():
    print("python -m tf_encrypted.player --config /tmp/tfe.config {}".format(player_name))
python -m tf_encrypted.player --config /tmp/tfe.config server0
python -m tf_encrypted.player --config /tmp/tfe.config server1
python -m tf_encrypted.player --config /tmp/tfe.config server2`

Can I ask is there any other method I can convert to tfe keras model?

**Comment by yanndupis** [comment]
Hey @Xusita ,

In the notebook, in order to work with `tfe.serving.QueueServer`, you have to launch three tfe servers. To launch the servers you don't have to run the notebook cell. You can open three terminals then in the the first terminal you run `python -m tf_encrypted.player --config /tmp/tfe.config server0`, in the second one `python -m tf_encrypted.player --config /tmp/tfe.config server1` etc. 

If you don't want to use `tfe.serving.QueueServer`and launch these tfe servers. You can run a private production with `tfe.LocalConfig` (used by default) as well. Here is an example:

```
import numpy as np
import tensorflow as tf

import tf_encrypted as tfe
from tf_encrypted.keras import backend as KE

num_classes = 10
input_shape = (1, 28, 28, 1)
input_data = np.random.normal(size=input_shape)

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Conv2D(2,
                                  (3, 3),
                                  batch_input_shape=input_shape))
model.add(tf.keras.layers.AveragePooling2D((2, 2)))
model.add(tf.keras.layers.Conv2D(2, (3, 3)))
model.add(tf.keras.layers.AveragePooling2D((2, 2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(num_classes, name="logit"))

expected = model.predict(input_data)

with tfe.protocol.SecureNN():
  x = tfe.define_private_input(
      "inputter",
      lambda: tf.convert_to_tensor(input_data))

  tfe_model = tfe.keras.models.clone_model(model)
  y = tfe_model(x)

with KE.get_session() as sess:
  actual = sess.run(y.reveal())

  np.testing.assert_allclose(actual, expected, rtol=1e-2, atol=1e-2)
```

Hope this help!

**Comment by yanndupis** [comment]
@Xusita does it solve your problem? If yes, I will close this issue. thanks

**Comment by mortendahl** [comment]
Closing for now; can reopen as needed.
