### ISSUE TITLE
Encrypt Trained TF models 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [tf-encrypted/tf-encrypted#714]
Hi, I have a question about encrypting TensorFlow models.  I have trained TensorFlow models using object detection API for custom object detection task. Now I want to provide the solution to the third party but I want to hide information i.e config files and weights etc information. I have to give them ready to use models configured in Jetson TX2 that they just need to run with some simple commands. Is it possible to encrypt the trained models and relevant files or any other possible solutions or suggestions, please?

**Comment by mortendahl** [comment]
Hi @MuhammadAsadJaved, you can in principle do this via one of the following options:

- ship your model inside an enclave (eg Intel SGX)

- homomorphically encrypt your model; however, you need someone to hold the decryption key and decrypt each prediction result

- secret share your model; however, this requires several parties to get involve every time the model is used, which may not be suitable for your setup

Can you give more details about how the model will be used and by who?
