### ISSUE TITLE
Join Slack-Channer

### ISSUE THREAD

**Issue by juanmixp** [tf-encrypted/tf-encrypted#717]
Hi @mortendahl 
This is not a real issue, but ... how can I join to slack channel?

Congratulations for your amazing work!

**Comment by mortendahl** [comment]
Hi @juanmixp, thank you for the heads up, the existing link seems to have expired. Here's is a new [Slack invite link](https://join.slack.com/t/tf-encrypted/shared_invite/enQtNjI5NjY5NTc0NjczLWM4MTVjOGVmNGFkMWU2MGEzM2Q5ZWFjMTdmZjdmMTM2ZTU4YjJmNTVjYmE1NDAwMDIzMjllZjJjMWNiMTlmZTQ).
