### ISSUE TITLE
How to feed data from local file in each data owner?

### ISSUE THREAD

**Issue by wuxibin89** [tf-encrypted/tf-encrypted#718]
Hi, I'm running `examples/logistic/training_joint.py`. At now, the training data (x_train_0, x_train_1) are randomly sampled using `tf.random.uniform`, which are naturally placed in data owner's device.  
In real world, we want to read data from local file. Suppose my session master is running in  server0,  I can create a dataset read in local file in server0, but how can I create a dataset  in server1?

**Comment by vincehong** [comment]
Yes, the examples are for local testing, you have to write your own code for *REAL* distributed use cases  like this;

      data_owner_0 = DataOwner('server1',
                                 '/path/on/alice/machine')

        data_owner_1 = DataOwner('server2',
                                 '/path/on/bob/machine'
                               )

The IP addresses of server1 and server2 has to be configured in TF config.json. Guess you should ask this question in Slack, it's a QA and not a issue of the code.

**Comment by mortendahl** [comment]
Hi @wuxibin89, is this still an issue?

**Comment by mortendahl** [comment]
Happy to reopen as needed, cc @wuxibin89.
