### ISSUE TITLE
Add explicit instructions for setting up VSCode

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#732]
We should offer a quick guide in `CONTRIBUTING.md` for setting up VSCode (among other editions), including help to set up a good `.vscode/settings.json` file.

Concrete suggestion:
```json
{
    "python.pythonPath": "</local/path/to/python/executable>",
    "python.formatting.provider": "yapf",
    "python.linting.enabled": true,
    "python.linting.mypyEnabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pydocstyleEnabled": true,
}
```

See https://code.visualstudio.com/docs/python/settings-reference for more.

**Comment by jvmancuso** [comment]
it would be great to automatically link the linter to the .pylintrc file as well

**Comment by mortendahl** [comment]
I was thinking to put everything in `setup.cfg` actually, thinking it's easier to make sure things align that way.

**Comment by jvmancuso** [comment]
as long as vscode & the content of pylintrc are talking, that works for me :)
