### ISSUE TITLE
Minor ABY3 test updates

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#736]
Minor updates:

- [x] rename `test_aby3.py` to `aby3_test.py` to match rest of code base
- [x] consider using `np.testing.assert_allclose(x, x, rtol=0.0, atol=threshold)` instead of custom `close` function (see https://github.com/tf-encrypted/tf-encrypted/pull/721/files#r362792674)
- [x] consider using `unittest.main()` at the end of the scripts instead of re-listing all test functions (which could potentially become unsynchronised in the future); see eg `pond_test.py`

**Comment by zicofish** [comment]
See [#741 ](https://github.com/tf-encrypted/tf-encrypted/pull/741)
