### ISSUE TITLE
crypto_producer accessed but not set

### ISSUE THREAD

**Issue by Arash-Afshar** [tf-encrypted/tf-encrypted#751]
From item 1 of  https://github.com/tf-encrypted/tf-encrypted/issues/749

The fix can be as simple as setting the crypto_producer in the `__init__`, but taking some care and grabbing it from `triple_source` when it is not None.

@mortendahl  what do you think?

On a different note, I started the work by creating a failing test and noticed a problem. Created https://github.com/tf-encrypted/tf-encrypted/issues/750

**Comment by mortendahl** [comment]
> The fix can be as simple as setting the crypto_producer in the __init__, but taking some care and grabbing it from triple_source when it is not None.

I think we should stick to triple source only, and move the two operations in question in under the triples sources and call the crypto producer from there. Triple sources represent strategies for generating triples, and different strategies may or may not have direct access to a crypto producer (if these are, say, generated offline).

It looks like the changes would look similar to how simpler operations like eg [`transpose`](https://github.com/tf-encrypted/tf-encrypted/blob/2edd1b7b217001ad24acb9bb637e90e6cee4ee70/tf_encrypted/protocol/pond/triple_sources.py#L99-L105) is handled.

**Comment by Arash-Afshar** [comment]
Ah, I see. I thought it would be part of another refactoring. Sure, I will change the PR :)

**Comment by mortendahl** [comment]
Thank you @Arash-Afshar!

**Comment by Arash-Afshar** [comment]
Submitted new changed. Decided to make triple_source accept values of multiple types instead of forcing all users of Pond to instantiate a TripleSource.

**Comment by mortendahl** [comment]
Closed by #753
