### ISSUE TITLE
HOW to encrypt a constant array

### ISSUE THREAD

**Issue by xiaobing0** [tf-encrypted/tf-encrypted#769]
I just want to know if we can use .revel() to decode, how to encrypt the constant array.  for example , in simple-average, if two sides are not various but constant, how to homomorphic encryption.

**Comment by mortendahl** [comment]
If I understand correctly, then you should be able to simple use the same method as there:

```python
def provide_input() -> tf.Tensor:
    return tf.constant([1, 2, 3, 4])
```
