### ISSUE TITLE
One session run, multiple predictions

### ISSUE THREAD

**Issue by bendecoste** [tf-encrypted/tf-encrypted#78]
We are currently using TF session.run() for each and every prediction. this is known to be sub-efficient.

In our case, it's a killer because TF spend sometimes optimizing the graph for each run and this time can be pretty big.

In production, served models should be loaded once and kept hot, listening for the next input to come. The goal here is to find an "in-between" solution to avoid tf.serving for now and yet be efficient with a python flask server.

**Comment by ianlivingstone** [comment]
Moving this out of prioritized as we've back burnered support for more than one inference request at a time. If anyone is looking for this feature, please don't hesitate to reply to this issue!

**Comment by mortendahl** [comment]
Fixed a while ago by making sure that the graph is not modified between session.runs.
