### ISSUE TITLE
Speeding up secure training with non-linear computation in linear networks

### ISSUE THREAD

**Issue by jvmncs** [tf-encrypted/tf-encrypted#780]
See [here](https://openai.com/blog/nonlinear-computation-in-linear-networks/) for context.

The basic idea here is to try to train a deep linear network with evolutionary strategies, similarly to how it's done in the post above. Clearly, the experiments there leave much to be desired, but having some code for the approach seems like a reasonable first step. The nonlinearity should be derived from Pond's fixed-point representation instead of the float32 mentioned in the post, which means the scalar will need to be tweaked to ensure activations end up in the proper nonlinearity range.

**Comment by vincehong** [comment]
Cool post, but I doubt it may be only useful in plaintext?
After all, the secret-shared values contain no information of whether the plaintext value is near "min" or not :/

**Comment by jvmncs** [comment]
The secret-shared tensors don't (e.g. PondTensor), but the underlying fixed-point precision tensors do (e.g. Int64Tensor). `min` can be determined from the parameters specified in FixedPointConfig
