### ISSUE TITLE
summary and trace files

### ISSUE THREAD

**Issue by shahashka** [tf-encrypted/tf-encrypted#781]
Hi,
Where are the summary and trace files written to? I'm running the federated learning example script. 
Thanks!

**Comment by jvmncs** [comment]
By default, summary files get written to `/tmp/tensorboard` (per [here](https://github.com/tf-encrypted/tf-encrypted/blob/b42d7affb7028f8b48b47962d1b9f3eeab3ef032/tf_encrypted/session.py#L16)). You can customize this location in two ways:
1. specify the TENSORBOARD_DIR environment variable when executing a TFE script (for example, `TENSORBOARD_DIR=/my/log/dir python run.py`)
2. specify it programmatically in your python script with `tfe.set_log_directory` (for example, in [this notebook](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/notebooks/Hello%20World.ipynb)
