### ISSUE TITLE
[Discussion] Sub-distributions

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#783]
We currently ship TFE as a single Python distribution, `tf-encrypted`, which includes both Python and C++ code. This makes the compilation process more involved than a simple `git clone ... && pip install -e .` as you need to have a range of build tools installed (including the right version of bazel). Especially MLers and cryptographers might benefit from doing (most of) their development in a pure-Python environment that can be compiled and tested using normal Python tools (and not bazel).

To get around this we could introduce a few sub-distributions, say:

- `tf-encrypted-core`: mixed code base containing e.g. custom ops
- `tf-encrypted-dev`: pure Python code base containing e.g. protocols and ML layers 

We precompile and distribute both of these to PyPI, allowing developers to install `tf-encrypted-core` using `pip` and `tf-encrypted-dev` using `git clone ... && pip install -e ...`. Both of them override any exiting installation of `tf-encrypted`, similarly to `tf-nightly` and `tensorflow`. Note that `tf-encrypted-core` will require e.g. bazel whereas `tf-encrypted-dev` can use standard Python tools.

We also continue to precompile and distribute `tf-encrypted` to PyPI since shipping a single distribution for non-development has some benefits, including mitigating versioning issues. I haven't been able to find a Python process/tool for doing this by statically linking official dependencies, but as an alternative we could avoid official dependencies and instead simply pull in their codebases and compile everything together. This should be manageable using bazel

Note that in the future we may introduce e.g. `tf-encrypted-runtime` for the mixed code base related to the secure runtime. This fits nicely with the above approach.

**Comment by mortendahl** [comment]
Here's a revision from discussions with @ianlivingstone.

This splits `tf-encrypted-core` into `tf-encrypted-primitives` (and potentially `tf-encrypted-compiler` and `tf-encrypted-runtime` down the line). It also reuses the `tf-encrypted` moniker for both the official package and what was `tf-encrypted-dev` above.

To install for non-development use: `pip install tf-encrypted`. This installs a standalone distribution without any dependencies (besides `tensorflow` and `numpy`). This will be the most common way of installing. It is built using bazel.

To install for development: `git clone tf-encrypted && cd tf-encrypted && pip install -e .`. This gives a pure-Python experience but you have to install additional distributions: for now just `pip install tf-encrypted-primitives`. 

To pull this off we may need the following structure in the `tf-encrypted` repo:

```
./build/setup.py  <-- used for official standalone 'tf-encrypted'

./primitives/tf_encrypted/primitives/**  <-- mixed code
./primitives/setup.py  <-- used for 'tf-encrypted-primitives'
./primitives/BUILD

./tf_encrypted/protocols/**  <-- pure-Python code
./tf_encrypted/keras/**  <-- pure-Python code
./setup.py  <-- used for dev installation of 'tf-encrypted' (without primitives)
```

**Comment by mortendahl** [comment]
Closing this with #782.

Have *not* worked on a unified package yet, so right now you'd need both `tf-encrypted` and `tf-encrypted-primitives`.

**Comment by jvmncs** [comment]
My one concern with this setup during the call was that this may lead to difficult times for infrequent contributors battling a CI that might not match their expectations. Concretely, what if someone changes a higher-level python package (like tfe.keras) which accidentally breaks a test from a package they haven't built locally. Do you have something in mind for preventing this kind of mismatch?

**Comment by mortendahl** [comment]
> what if someone changes a higher-level python package (like tfe.keras) which accidentally breaks a test from a package they haven't built locally. Do you have something in mind for preventing this kind of mismatch?

I'm imagining acyclic dependencies, at least for higher level functionality like TFE Keras. Eventually we might have something like the following (where `core` is different and lower-level than the `tf-encrypted-core` mentioned in [the first comment](https://github.com/tf-encrypted/tf-encrypted/issues/783#issue-590978755); think base types etc.):

```
core

primitives
  -> core

protocols
  -> core
  -> primitives

keras
  -> core
```

This should ensure that no higher-level (ie pure-Python) code can break precompiled packages. The latter may of course fall short of functionality, but in this case you'd have to go all in leave Python Wonderland.

Would this solve your concerns?

**Comment by jvmncs** [comment]
I think so! To make sure I understand, all the `core` subdirectories would be standalone Python? And e.g. `protocols/core` would optionally depend on `protocols/primitives`, which would only be built for the `tf-encrypted-core` package from above. And then the `tf-encrypted-dev` package would only depend on the `core` subdirectory for each of these?

**Comment by mortendahl** [comment]
Not sure we're interpreting the graph in the same way. In the following `protocols` depends on `core` and `primitives`:

```
protocols
  -> core
  -> primitives
```

`core` could likely be a precompiled package as well, making the precompiled packages less fragile (can't break precompiled without compiling). Wanted to stay away from optionally dependency as much as possible since it gives more code paths to test.

**Comment by mortendahl** [comment]
Offline discussions lead to consensus. Key point was that we won't allow fallback functionality in the future (ie around randomness) so there will never be e.g. non-compiled and pre-compiled functions that are expected to match.
