### ISSUE TITLE
Incessant running of the 'clone_model()' function

### ISSUE THREAD

**Issue by simbathla** [tf-encrypted/tf-encrypted#792]
I have trained my model using Differential Privacy, and now I wish to serve it securely for private predictions. I have used TF-Encrypted for the same, SecureNN is the protocol. My model is Keras Sequential model. 
When I have to convert my model from Tensorflow to TF-Encrypted, I run the following command
'with tfe.protocol.SecureNN():
  tfe_model = tfe.keras.models.clone_model(model)'
But, the cell never stops running. It shows a few warnings, but doesn't complete, even after hours of running. 
I am attaching the screenshot of the same for your kind perusal. Please help me in finding out what is wrong.
![Clone_Model](https://user-images.githubusercontent.com/54496363/79052418-0323db00-7c54-11ea-995a-978ceb45f050.png)

**Comment by jvmncs** [comment]
Hi, can you please share code to help us reproduce your issue? Thanks for trying out our project.

**Comment by simbathla** [comment]
Hi!

I have done this work on Google Colab. I am sharing all the three python notebooks with you, which include the preprocessing and feature extraction, training with Differential Privacy and securely serving the model.
Thankyou for your support.

**Comment by simbathla** [comment]
Hi!
Were you able to spot some issue in my code? 

Regards
Simran

**Comment by securedlm** [comment]
@mortendahl and jvmncs pl look into the matter. I am also facing similar type of error.

**Comment by jvmncs** [comment]
Hi @simbathla @securedlm, please share code that we can refer to when trying to reproduce your issue. @simbathla it appears your colab/ipynb notebook was never attached to your comment.

**Comment by simbathla** [comment]
Hi @jvmncs, please access the colab notebooks using the link below:
https://drive.google.com/open?id=1TYOgGpphTHg41eE79jKkPmqfa5fjQ-lx
Thanks.

**Comment by securedlm** [comment]
any update @mortendahl  @jvmncs

**Comment by securedlm** [comment]
please look into the matter as soon as possible @jvmncs

**Comment by jvmncs** [comment]
@simbathla I'm still getting an error when trying to open those notebooks with Google Colab. You may need to update the permissions on the notebooks themselves in addition to that folder, if you haven't already.

**Comment by securedlm** [comment]
@ simbathla please update the permission. Change permission to anyone can  access this file with the link

**Comment by simbathla** [comment]
@jvmncs, I have updated the permission. Also, I have attached the notebooks and mailed them to the email address 'jason@capeprivacy.com', which I believe belongs to you. 
@securedlm, I apologise, I cannot reveal the code  to everyone.

**Comment by simbathla** [comment]
@jvmncs, any update?

**Comment by jvmncs** [comment]
Was able to access the notebooks. In cell 18 of `Cance_logit_model_serving_shared.ipynb`, we print out the commands you need to run to spin up TF devices for the tf_encrypted players. How are these being run in Colab? Those commands are meant to be executed in different terminal processes, but it seems like they're just being printed out for now.

Alternatively, if you just want to do a local simulation on a single machine, you can remove the sections where you make a new config and just use the TFE default config.

**Comment by jvmncs** [comment]
Hi @simbathla, were you able to solve this issue? Closing now, feel free to reopen or open a new issue if you have anything else

**Comment by simbathla** [comment]
Hi @jvmncs , I apologise as I was a little busy and couldn't answer you on time. 
I wrote the same code for model serving in the Jupyter Notebook creating the new config, three servers, and tried to run the following command on three different terminals.

for player_name in players.keys():
  print("python3.6 m tf-encrypted.player --config /tmp/tfe.config {}".format(player_name))

But there seems to be some error. 
Could you please tell me about the exact commands that are supposed to be written on the terminal in order to launch the TFE Servers.
