### ISSUE TITLE
tf 2.x support

### ISSUE THREAD

**Issue by peter197321** [tf-encrypted/tf-encrypted#799]
does the tf-encrypted framework support TensorFlow 2.x?if not, what's the plan to upgrade tf-encrypted to TensorFlow 2.x?

**Comment by SamuelGong** [comment]
same question here

**Comment by chaisan** [comment]
same here!

**Comment by jvmncs** [comment]
Hi all, thanks for your interest here!

The short answer: We're currently in the middle of a planning phase for our TFE 1.x roadmap. We're all super excited about that, and the new features it will bring. All the details haven't been ironed out yet, but we've all agreed that TFE 1.x will be TF 2.x-compatible. We may still update the TFE 0.x codebase to TF 2.x sometime before then, but we don't have concrete plans to do that yet.

TFE has been mostly [experimental](https://github.com/tf-encrypted/tf-encrypted/tree/master#project-status) and research-oriented so far. Now that we've learned its advantages & limitations, we feel that it would be best to put our efforts into rebuilding it "the right way". We'll continue to accept bug reports & pull requests for 0.x, and will likely publish at least one more release of 0.x to provide a stable version for future reference.

As mentioned in the past (#679), we'd originally planned to have TF 2.x support in a TFE 0.6.0 release. The [master-tf2](https://github.com/tf-encrypted/tf-encrypted/tree/master-tf2) branch was where we'd planned to do this. However, converting the codebase to use TF 2.0 constructs like `tf.function` as done in that branch requires a nontrivial amount of work, in particular to ensure the same level of security and speed we have in TF 1.x. You can play around with it as it exists there if you're interested, but it's unlikely we'll merge that branch into master.

**Comment by vincehong** [comment]
TFE 0.9.0 now supports TF2.
