### ISSUE TITLE
Change share type in SecureNN

### ISSUE THREAD

**Issue by liao1230ho123** [tf-encrypted/tf-encrypted#805]
Dear developers,
Its very thankful for your effort to provide this project. The whole thing is wonderful although I faced some problems building some required library such as secure randomness in my environment( Windows and Ubuntu). Also, while using pip install command the project doesnt contain ABY3 protocol, it is very helpful to add this protocol into pre-build pip package!

**Comment by jvmncs** [comment]
Hi, we don't have a release planned yet, but our next release will include ABY3 in the pip package! You can find more info about our upcoming plans [here](https://github.com/tf-encrypted/tf-encrypted/issues/799#issuecomment-636127262).

**Comment by zicofish** [comment]
ABY3 comes as the default in version [0.7.0](https://github.com/tf-encrypted/tf-encrypted/tree/0.7.0)
