### ISSUE TITLE
Any examples for using ABY3 protocol ?

### ISSUE THREAD

**Issue by liao1230ho123** [tf-encrypted/tf-encrypted#807]
Hi,
I have used the examples in examples directory already but most are for SecureNN and Pond but I would like to use ABY3.
Is there any examples or notebook for using ABY3 protocol?  for Multiplication operation is better.
I found that ABY3 dosent contain using Queue fuction so I faced troubles for experimenting.

Very appreciate!

**Comment by jvmncs** [comment]
[Here's](https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/protocol/aby3/model/logistic_regression.py) some code to help with training a linear classifier with ABY-3, similar to the original logistic regression example. You can use those classes to write your own training script.

As far as using ABY-3 with the Queue, I don't think we've tested it. It should be possible in theory though!

**Comment by vincehong** [comment]
Please check the examples on ML inference and training on secret-shared images.  https://github.com/tf-encrypted/tf-encrypted/tree/master/examples/benchmark
