### ISSUE TITLE
Training Logistic Regression model meets Error: 'PondPrivateTensor' object has no attribute 'to_native'

### ISSUE THREAD

**Issue by giraffeCjl** [tf-encrypted/tf-encrypted#808]
When I was training a logistic regression model, 20 epochs ended with an error attribute error:'pond private tensor object has no attribute to_native. The source seems to be here tf_encrypted/utils.py  in unwrap_fetches return fetches.to_native().

**Comment by jvmncs** [comment]
Hi, do you have any code that can reproduce the error?

**Comment by giraffeCjl** [comment]
> Hi, do you have any code that can reproduce the error?

Thank you very much, the problem has been solved.

**Comment by boris-vasilev** [comment]
Hi, could you tell me how you fixed it? I was trying to run the logistic regression as well and got stuck at the same stage.
