### ISSUE TITLE
How to set tfe.protocol With many players ("more than 3")

### ISSUE THREAD

**Issue by Mdjosephe** [tf-encrypted/tf-encrypted#810]
When I look into the definitions of the protocols Pond, ABY3 and SecureNN, I can't find a way to set any of them for more than 3 players ? is that possible ?

**Comment by jvmncs** [comment]
The short answer; no, that's not currently possible. TFE only implements protocols which use three non-colluding parties.  The hostnames provided by the tfe.Config class are those same parties, but it must always match the number of parties expected by the specific tfe.Protocol being used (in our case it's always 3 parties).

If you have more than 3 parties that want to provide data however, you can specify them as input providers the way it's done in the examples. We sometimes refer to this as the "outsourced" setting for encrypted ML.

**Comment by zicofish** [comment]
Implementation of more-than-3 pc computation might not happen in the near future. We can reopen this discussion if it will be included in a plan.
