### ISSUE TITLE
Errors when running ABY3_test.py

### ISSUE THREAD

**Issue by TianshuoCong** [tf-encrypted/tf-encrypted#811]
Hi!
When I tried to run tf-encrypted/protocol/aby3/ABY3_test.py, I met some errors as follows.
(MacOS, python 3.6.1, tf 1.15.3)

<img width="537" alt="截屏2020-07-09 上午12 01 02" src="https://user-images.githubusercontent.com/21216238/86944072-d2334380-c179-11ea-8556-ae3084074845.png">

Thanks for your help!

**Comment by jvmncs** [comment]
Hi, have you followed the development installation instructions found [here](https://github.com/tf-encrypted/tf-encrypted/blob/master/docs/INSTALL.md#custom-ops)?

**Comment by TianshuoCong** [comment]
It works for me! 
I just installed tfe via pip for convenience and ignore that...

Thank you for your reply :)

**Comment by TianshuoCong** [comment]
One more question, where can I find the paper about the pond protocol?
I want to read some details but could not find the link or something.
Thx!

**Comment by jvmncs** [comment]
You can find a description of Pond in Section 2 of our [NeurIPS workshop paper](https://arxiv.org/abs/1810.08130). Because we implement/combine primitives from previous work, we rely on the security proofs from those papers.
