### ISSUE TITLE
When can tfe support the transformation of RNN models such as LSTM?

### ISSUE THREAD

**Issue by giraffeCjl** [tf-encrypted/tf-encrypted#813]
It seems that the current Sequential layers provided by tfe include Dense, Conv2D, etc. When will tfe supporting LSTM be available? Looking forward to

**Comment by zicofish** [comment]
Indeed, this might be an important scenario in the plain world. But in the MPC world, we haven't found an urgent use case for the requirement of RNN models. Will mark this as a long-term TODO item.
