### ISSUE TITLE
Support for Non-Keras TensorFlow Code?

### ISSUE THREAD

**Issue by allenkim** [tf-encrypted/tf-encrypted#815]
Hi,

I was wondering if one could write non-Keras TensorFlow code and convert that into a secure version. It seems the examples all make use of Keras (unless I missed something?).

Thank you!

**Comment by jvmncs** [comment]
Hi, take a look at the [graph converter](https://github.com/tf-encrypted/tf-encrypted/tree/master/tf_encrypted/convert). It predates our Keras interface, and it's not very polished, but it can be used to attempt an auto-conversion. There is also a guide there for adding new conversions to account for graph operations/subgraphs that TFE can't identify directly

**Comment by allenkim** [comment]
Thanks for the quick reply!
