### ISSUE TITLE
Curated onboarding experience for contributors

### ISSUE THREAD

**Issue by bendecoste** [tf-encrypted/tf-encrypted#82]
We want to make it easy for anyone to get up and running with tf-encrypted and help them contribute to the project.

It'd be nice for us to setup the following:

- Write up contributor guidelines including how to get started with development, expectations around issue management, pull requests templates, etc.
- A code of conduct which states our expectation for how everyone who works on the project interacts with one another.
- A slew of issues labeled as help wanted / good first issue that are clear, concise, and actionable to make it easy for someone to jump and start moving the ball forward.

Thats a few of the things we can do to improve/create an onboarding experience for contributors to the project.

I think these things would make it easier for us to do our work as well!

**Comment by mortendahl** [comment]
Closing this up as we now have all of the above. There are still plenty of things to do but let's open a new issue for that.
