### ISSUE TITLE
ABY3 error：Unsupported share type: 0.

### ISSUE THREAD

**Issue by hgyuhaoyang** [tf-encrypted/tf-encrypted#830]
Dear developers:
I tried to use tfe.reshape() function with ABY3 protocol, but the program reports an error：Unsupported share type: 0.
I printed share_type of cipher using pond protocol, but there is no share type of pond protocol cipher. 
I wanna know how to use tfe.reshape() function with ABY3 protocol, thanks a lot.

``"""Private training on combined data from several data owners"""

import tensorflow as tf
import tf_encrypted as tfe
from tf_encrypted.protocol.aby3 import ABY3

def maaain(server):
    w = tfe.define_private_variable(tf.ones(shape=(10, 10)))
    print("w: ",type(w))
    x = tfe.define_private_variable(tf.ones(shape=(5, 10)))
    print("x: ",type(x))
    y = tfe.matmul(x, w)
    print("x.share_type = ",x.share_type)
    a = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
    a = tf.convert_to_tensor(a)
    a = tfe.define_private_variable(a)
    index_a = tf.Variable([0, 2])
    b = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    index_b = tf.Variable([2, 4, 6, 8])
    with tfe.Session() as sess:
        sess.run(tfe.global_variables_initializer(),
                 tag='init')
        print(sess.run(tfe.gather(a, index_a,axis=1)))

def start_master(cluster_config_file=None):
    print("Starting alice...")
    remote_config = tfe.RemoteConfig.load(cluster_config_file)
    tfe.set_config(remote_config)
    players = remote_config.players
    server0 = remote_config.server(players[0].name)
    prot = ABY3("alice","bob","carl")
    tfe.set_protocol(prot)
    maaain(server0)

if __name__ == "__main__":
    TFE_EVENTS = 1
    start_master("config.json")

**Comment by wuxuedaifu** [comment]
[hadoop @ svr9626 jd_feature]$ cat
jd_feature_disc.py
# coding=utf-8
## import modules and functions
import sys

reload(sys)
sys.setdefaultencoding('utf-8')
import time, datetime
from datetime import datetime, timedelta, date
from pyspark.sql import SparkSession
from pyspark.sql.types import IntegerType, StringType
from pyspark.sql.functions import udf, col, to_date, months_between
import pyspark.sql.functions as func
import pyspark.sql.types as typ

### start spark session
t_start = int(time.time())
spark = SparkSession.builder.enableHiveSupport() \
    .master("spark://svr9625:7077") \
    .appName("jd_feature_disc") \
    .config("spark.executor.cores", "4") \
    .config("spark.executor.memory", "10g") \
    .getOrCreate()
spark.sparkContext.setLogLevel('ERROR')

### 自动更新时间参数
today = date.today()
years, months = today.year, today.month
com_mon = years * 100 + (months - 1)
cur_dt = years * 10000 + months * 100 + 1
## create table for the discretized
spark.sql('''
create table workspace_sms.jd_feature_all_disc_%d(
mobile string,jd_default_cnt_3m integer,\
jd_shopDefault_cnt_3m integer,jd_shopRepay_cnt_3m integer,jd_autoRepayFail_cnt_3m integer,\
jd_BTloan_cnt_3m integer,jd_loan_cnt_3m integer,jd_BTquick_cnt_3m integer,jd_BillInstallment_cnt_3m integer,\
jd_BTcash_cnt_3m integer,jd_repay_cnt_3m integer,jd_houseRepay_cnt_12m integer,\
jd_default_cnt_12m integer,jd_default_maxCumulCnt_12m integer,jd_shopDefault_cnt_12m integer,\
jd_shopRepay_cnt_12m integer,jd_autoRepayFail_cnt_12m integer,jd_BTloan_cnt_12m integer,\
jd_loan_cnt_12m integer,jd_BTquick_cnt_12m integer,jd_BillInstallment_cnt_12m integer,\
jd_BTcash_cnt_12m integer,jd_repay_cnt_12m integer,jd_shopDefault_amt_3m integer,\
jd_shopRepay_amt_3m integer,jd_autoRepayFail_amt_3m integer,jd_BTloan_amt_3m integer,\
jd_loan_amt_3m integer,jd_BTquick_amt_3m integer,jd_BillInstallment_amt_3m integer,\
jd_BTcash_amt_3m integer,jd_repay_amt_3m integer,jd_monRepay_maxAmt_3m integer,\
jd_BillInstallment_minAmt_3m integer,jd_houseRepay_avgAmt_12m integer,jd_shopDefault_amt_12m integer,\
jd_shopRepay_amt_12m integer,jd_autoRepayFail_amt_12m integer,jd_BTloan_amt_12m integer,\
jd_loan_amt_12m integer,jd_BTquick_amt_12m integer,jd_BillInstallment_amt_12m integer,\
jd_BTcash_amt_12m integer,jd_repay_amt_12m integer,jd_monRepay_maxAmt_12m integer,\
jd_BillInstallment_minAmt_12m integer,jd_BTloan_cntGR_3m double,jd_BTloan_amtGR_3m double,\
jd_loan_cntGR_3m double,jd_loan_amtGR_3m double,jd_BillInstallment_cntGR_3m double,\
jd_BillInstallment_amtGR_3m double,jd_BTloan_cntGR_6m double,jd_BTloan_amtGR_6m double,\
jd_loan_cntGR_6m double,jd_loan_amtGR_6m double,jd_BillInstallment_cntGR_6m double,\
jd_BillInstallment_amtGR_6m double,jd_BT_limitAmt integer,jd_JT_limitAmt integer,\
jd_BT_timeDiff integer,jd_JT_timeDiff integer,jd_if_houseRepay integer,jd_if_default integer)
''' % (com_mon))

### calculate features
mob = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f']
for i in range(len(mob)):
    print(mob[i], 'is ready!')
    feature = spark.sql('''
        select * from workspace_sms.jd_feature_all_%d where substring(mobile,0,1) = '%s' ''' % (com_mon, str(mob[i])))
    feature.persist()
    print('本月标签:')
    print(feature.show(5))


    # 次数离散化
    def cnt_disc(x):
        if x >= 0 and x < 1:
            return 0
        elif x >= 1 and x < 2:
            return 1
        elif x >= 2 and x < 5:
            return 2
        elif x >= 5 and x < 10:
            return 3
        elif x >= 10 and x < 20:
            return 4
        elif x >= 20 and x < 50:
            return 5
        elif x >= 50 and x < 80:
            return 6
        elif x >= 80 and x < 120:
            return 7
        elif x >= 120 and x < 200:
            return 8
        elif x >= 200:
            return 9
        else:
            return 0


    func_cnt = udf(cnt_disc, IntegerType())


    # 金额离散化
    def amt_func(x):
        if x >= 0 and x < 1:
            return 0
        elif x >= 1 and x < 500:
            return 1
        elif x >= 500 and x < 1000:
            return 2
        elif x >= 1000 and x < 3000:
            return 3
        elif x >= 3000 and x < 5000:
            return 4
        elif x >= 5000 and x < 7000:
            return 5
        elif x >= 7000 and x < 10000:
            return 6
        elif x >= 10000 and x < 15000:
            return 7
        elif x >= 15000 and x < 20000:
            return 8
        elif x >= 20000 and x < 30000:
            return 9
        elif x >= 30000 and x < 50000:
            return 10
        elif x >= 50000 and x < 100000:
            return 11
        elif x >= 100000 and x < 200000:
            return 12
        elif x >= 200000 and x < 500000:
            return 13
        elif x >= 500000:
            return 14
        else:
            return 0


    func_amt = udf(amt_func, IntegerType())


    # 额度离散化
    def limit_func(x):
        if x >= 0 and x < 1:
            return 0
        elif x >= 1 and x < 500:
            return 1
        elif x >= 500 and x < 1000:
            return 2
        elif x >= 1000 and x < 3000:
            return 3
        elif x >= 3000 and x < 5000:
            return 4
        elif x >= 5000 and x < 7000:
            return 5
        elif x >= 7000 and x < 10000:
            return 6
        elif x >= 10000 and x < 15000:
            return 7
        elif x >= 15000 and x < 20000:
            return 8
        elif x >= 20000 and x < 30000:
            return 9
        elif x >= 30000 and x < 50000:
            return 10
        elif x >= 50000 and x < 100000:
            return 11
        elif x >= 100000 and x < 200000:
            return 12
        elif x >= 200000 and x < 500000:
            return 13
        elif x >= 500000:
            return 14
        else:
            return -1


    func_limit = udf(limit_func, IntegerType())
    df_disc = feature.select('mobile', func_cnt(feature.due_cnt_3m).alias('jd_default_cnt_3m'), \
                             func_cnt(feature.storedue_cnt_3m).alias('jd_shopDefault_cnt_3m'), \
                             func_cnt(feature.repay_cnt_3m).alias('jd_shopRepay_cnt_3m'), \
                             func_cnt(feature.fail_cnt_3m).alias('jd_autoRepayFail_cnt_3m'), \
                             func_cnt(feature.use_bt_cnt_3m).alias('jd_BTloan_cnt_3m'), \
                             func_cnt(feature.loan_cnt_3m).alias('jd_loan_cnt_3m'), \
                             func_cnt(feature.bt_quickpass_cnt_3m).alias('jd_BTquick_cnt_3m'), \
                             func_cnt(feature.billfq_cnt_3m).alias('jd_BillInstallment_cnt_3m'), \
                             func_cnt(feature.withdraw_cnt_3m).alias('jd_BTcash_cnt_3m'), \
                             func_cnt(feature.repayment_cnt_3m).alias('jd_repay_cnt_3m'), \
                             func_cnt(feature.houseLoan_cnt_12m).alias('jd_houseRepay_cnt_12m'), \
                             func_cnt(feature.due_cnt_12m).alias('jd_default_cnt_12m'), \
                             func_cnt(feature.due_accum_cnt_12m).alias('jd_default_maxCumulCnt_12m'), \
                             func_cnt(feature.storedue_cnt_12m).alias('jd_shopDefault_cnt_12m'), \
                             func_cnt(feature.repay_cnt_12m).alias('jd_shopRepay_cnt_12m'), \
                             func_cnt(feature.fail_cnt_12m).alias('jd_autoRepayFail_cnt_12m'), \
                             func_cnt(feature.use_bt_cnt_12m).alias('jd_BTloan_cnt_12m'), \
                             func_cnt(feature.loan_cnt_12m).alias('jd_loan_cnt_12m'), \
                             func_cnt(feature.bt_quickpass_cnt_12m).alias('jd_BTquick_cnt_12m'), \
                             func_cnt(feature.billfq_cnt_12m).alias('jd_BillInstallment_cnt_12m'), \
                             func_cnt(feature.withdraw_cnt_12m).alias('jd_BTcash_cnt_12m'), \
                             func_cnt(feature.repayment_cnt_12m).alias('jd_repay_cnt_12m'), \
                             func_amt(feature.storedue_amount_3m).alias('jd_shopDefault_amt_3m'), \
                             func_amt(feature.repay_amount_3m).alias('jd_shopRepay_amt_3m'), \
                             func_amt(feature.fail_amount_3m).alias('jd_autoRepayFail_amt_3m'), \
                             func_amt(feature.use_bt_amount_3m).alias('jd_BTloan_amt_3m'), \
                             func_amt(feature.loan_amount_3m).alias('jd_loan_amt_3m'), \
                             func_amt(feature.bt_quickpass_amount_3m).alias('jd_BTquick_amt_3m'), \
                             func_amt(feature.billfq_amount_3m).alias('jd_BillInstallment_amt_3m'), \
                             func_amt(feature.withdraw_amount_3m).alias('jd_BTcash_amt_3m'), \
                             func_amt(feature.repayment_amount_3m).alias('jd_repay_amt_3m'), \
                             func_amt(feature.repay_maxamt_3m).alias('jd_monRepay_maxAmt_3m'), \
                             func_amt(feature.billfq_minamt_3m).alias('jd_BillInstallment_minAmt_3m'), \
                             func_amt(feature.houseLoan_avg_12m).alias('jd_houseRepay_avgAmt_12m'), \
                             func_amt(feature.storedue_amount_12m).alias('jd_shopDefault_amt_12m'), \
                             func_amt(feature.repay_amount_12m).alias('jd_shopRepay_amt_12m'), \
                             func_amt(feature.fail_amount_12m).alias('jd_autoRepayFail_amt_12m'), \
                             func_amt(feature.use_bt_amount_12m).alias('jd_BTloan_amt_12m'), \
                             func_amt(feature.loan_amount_12m).alias('jd_loan_amt_12m'), \
                             func_cnt(feature.bt_quickpass_amount_12m).alias('jd_BTquick_amt_12m'), \
                             func_amt(feature.billfq_amount_12m).alias('jd_BillInstallment_amt_12m'), \
                             func_amt(feature.withdraw_amount_12m).alias('jd_BTcash_amt_12m'), \
                             func_amt(feature.repayment_amount_12m).alias('jd_repay_amt_12m'), \
                             func_amt(feature.repay_maxamt_12m).alias('jd_monRepay_maxAmt_12m'), \
                             func_amt(feature.billfq_minamt_12m).alias('jd_BillInstallment_minAmt_12m'), \
                             'usebt_cnt_stat_3m', 'usebt_amt_stat_3m', 'loan_cnt_stat_3m', 'loan_amt_stat_3m', \
                             'billfq_cnt_stat_3m', 'billfq_amt_stat_3m', 'usebt_cnt_stat_6m', 'usebt_amt_stat_6m', \
                             'loan_cnt_stat_6m', 'loan_amt_stat_6m', 'billfq_cnt_stat_6m', 'billfq_amt_stat_6m', \
                             func_limit(feature.bt_amount).alias('jd_BT_limitAmt'), \
                             func_limit(feature.jt_amount).alias('jd_JT_limitAmt'), \
                             'bt_earliest_time', 'jt_earliest_time', 'isdue', 'ishouseLoan')
    df_disc = df_disc.withColumn('bt_earliest_time', df_disc['bt_earliest_time'].cast(StringType()))
    df_disc = df_disc.withColumn('jt_earliest_time', df_disc['jt_earliest_time'].cast(StringType()))
    df_disc = df_disc.withColumn('bt_earliest_time', to_date(to_date('bt_earliest_time', 'yyyyMMdd')))
    df_disc = df_disc.withColumn('jt_earliest_time', to_date(to_date('jt_earliest_time', 'yyyyMMdd')))
    df_disc = df_disc.withColumn('today', func.lit(cur_dt))
    df_disc = df_disc.withColumn('today', df_disc['today'].cast(StringType()))
    df_disc = df_disc.withColumn('today', to_date(to_date('today', 'yyyyMMdd')))
    df_disc = df_disc.withColumn('jd_BT_timeDiff', func.ceil(months_between(df_disc.today, df_disc.bt_earliest_time)))
    df_disc = df_disc.withColumn('jd_JT_timeDiff', func.ceil(months_between(df_disc.today, df_disc.jt_earliest_time)))
    df_disc = df_disc.drop('bt_earliest_time').drop('jt_earliest_time').drop('today')
    df_disc = df_disc.withColumn("jd_BT_timeDiff", df_disc["jd_BT_timeDiff"].cast(IntegerType())).withColumn(
        "jd_JT_timeDiff", df_disc["jd_JT_timeDiff"].cast(IntegerType()))
    df_disc = df_disc.withColumnRenamed('usebt_cnt_stat_3m', 'jd_BTloan_cntGR_3m') \
        .withColumnRenamed('usebt_amt_stat_3m', 'jd_BTloan_amtGR_3m') \
        .withColumnRenamed('loan_cnt_stat_3m', 'jd_loan_cntGR_3m') \
        .withColumnRenamed('loan_amt_stat_3m', 'jd_loan_amtGR_3m') \
        .withColumnRenamed('billfq_cnt_stat_3m', 'jd_BillInstallment_cntGR_3m') \
        .withColumnRenamed('billfq_amt_stat_3m', 'jd_BillInstallment_amtGR_3m') \
        .withColumnRenamed('usebt_cnt_stat_6m', 'jd_BTloan_cntGR_6m') \
        .withColumnRenamed('usebt_amt_stat_6m', 'jd_BTloan_amtGR_6m') \
        .withColumnRenamed('loan_cnt_stat_6m', 'jd_loan_cntGR_6m') \
        .withColumnRenamed('loan_amt_stat_6m', 'jd_loan_amtGR_6m') \
        .withColumnRenamed('billfq_cnt_stat_6m', 'jd_BillInstallment_cntGR_6m') \
        .withColumnRenamed('billfq_amt_stat_6m', 'jd_BillInstallment_amtGR_6m')
    df_disc = df_disc.withColumn('jd_if_houseRepay', df_disc['ishouseLoan'].cast(IntegerType()))
    df_disc = df_disc.withColumn('jd_if_default', df_disc['isdue'].cast(IntegerType()))
    df_disc = df_disc.drop('isdue').drop('ishouseLoan')
    df_disc = df_disc.fillna(-1, subset=['jd_BTloan_cntGR_6m', 'jd_BTloan_amtGR_6m', \
                                         'jd_loan_cntGR_6m', 'jd_loan_amtGR_6m', 'jd_BillInstallment_cntGR_6m', \
                                         'jd_BillInstallment_amtGR_6m', 'jd_BTloan_cntGR_3m', 'jd_BTloan_amtGR_3m', \
                                         'jd_loan_cntGR_3m', 'jd_loan_amtGR_3m', 'jd_BillInstallment_cntGR_3m', \
                                         'jd_BillInstallment_amtGR_3m'])
    # df_disc = df_disc.fillna(0, subset = ['jd_BT_timeDiff','jd_JT_timeDiff'])
    df_disc = df_disc.fillna(0)
    df_disc.write.mode('append').insertInto('workspace_sms.jd_feature_all_disc_%d' % (com_mon), overwrite=False)
    print('本次存入标签:')
    spark.sql('''select * from workspace_sms.jd_feature_all_disc_%d where substring(mobile,0,1) = '%s' ''' % (
    com_mon, str(mob[i]))).show(5)
    print(mob[i], 'complete!')
