### ISSUE TITLE
Is tf-encrypted using BFV scheme or CKKS scheme in Microsoft SEAL?

### ISSUE THREAD

**Issue by kasundharmadasa** [tf-encrypted/tf-encrypted#831]
What scheme (BFV or CKKS) is being used by the tfe.matmul() function in the tf-encrypted library?

**Comment by 7feilee** [comment]
> What scheme (BFV or CKKS) is being used by the tfe.matmul() function in the tf-encrypted library?

1. tfe.matmul() funtion uses secret share to generate a matmul triple, you can check the [code](https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/protocol/pond/triple_sources.py#L74:1)  in spdz protocol inplementation.
2. Of course, you can use homomorphic encryption to generate a matmul triple to achieve two parties secure computation.

**Comment by vincehong** [comment]
tfe.matmul() uses secret-sharing techniques (https://mortendahl.github.io/2017/06/04/secret-sharing-part1/) but not FHE techniques, so BFV/CKKS is not used here.
