### ISSUE TITLE
aby3 how to save

### ISSUE THREAD

**Issue by WhiteCatInTheDaytime** [tf-encrypted/tf-encrypted#834]
ABY3 : 怎么保存计算结果到某个节点,而不是所有节点. 保存到文件
Aby3: how to save the results(ABY3PrivateTensor) to a node instead of all nodes. Save to a file

**Comment by zicofish** [comment]
In the current version, there is no convenient way to do this in a single line of code. 
But you can achieve this purpose with the following:

First call `prot._reconstruct` to reconstruct the result to a specific node,
then use TF's `TFRecordWriter` and `tf.device` to save the result to that node (check `_write_private` for how to write to a file on a specific device).

This is a nice feature to have. We will add it soon.
