### ISSUE TITLE
Implementaion of Division in SecureNN

### ISSUE THREAD

**Issue by psy-mas** [tf-encrypted/tf-encrypted#839]
Hello. Is there a short-term plan to implement division in SecureNN??

**Comment by zicofish** [comment]
@psy-mas AFAIK, there is no plan to implement this in a short term.
But I do have an internal version of ABY3 that supports floating point division.
We can discuss about this further if you are interested.

**Comment by psy-mas** [comment]
@zicofish THX for commenting. Do you mean performing a true division of 'x' by y where 'y'  is public? I am now very curious about how to perform a division of 'x' by 'y' where both of them are private(e.g. the implementation in SecureNN or Newton-Raphson,Goldschmidt algorithm etc.)
Best wishes.

**Comment by zicofish** [comment]
@psy-mas I was also talking about the scenario where both are private, but we only implemented this for the ABY3 scheme.

**Comment by psy-mas** [comment]
@zicofish Hey，I am really interested in this.Would you like to tell me how to implement that in the ABY3 scheme?Appreciate it very much.
Best wishes.

**Comment by vincehong** [comment]
> @zicofish Hey，I am really interested in this.Would you like to tell me how to implement that in the ABY3 scheme?Appreciate it very much.
> Best wishes.

The idea is similar with this paper of ours :https://dl.acm.org/doi/abs/10.1145/3411501.3419427 .

**Comment by psy-mas** [comment]
Hey, thank you very much for the replying @vincehong . Nice job!! I am going to read this paper carefully!

Best wishes
