### ISSUE TITLE
How to delete the method of data segmentation in pond

### ISSUE THREAD

**Issue by CHIALAN1** [tf-encrypted/tf-encrypted#841]
In my scenario, I want to give the share that I have already done to two servers directly and then train the model. Every time I call the pond, the plaintext share will be divided again. Is there any way to delete the division in the pond without affecting the following calculation

**Comment by zicofish** [comment]
@CHIALAN1 Mark this in a TODO list. Pond does not support it yet, but ABY3 has a method that might solve your issue: [`read`](https://github.com/tf-encrypted/tf-encrypted/blob/bbc53ecc4d74e198edb29b6ceb71ffdcc417a778/tf_encrypted/protocol/aby3/aby3.py#L1194)
