### ISSUE TITLE
Is there any API for computation party to get its own local plaintext

### ISSUE THREAD

**Issue by gogogo66** [tf-encrypted/tf-encrypted#842]
In the process of multi-party secure computing, the participant is both the data owner and the computation party. When executing the mpc protocol, the participant wants to obtain its own local plaintext secrets (including some intermediate results). 
For example, participant A and B want to compute a+b, then A shares a for a1,a2(keeping a1 and sending a2 to B), B shares b1,b2(keeping b2 and sending b1 to A),I want A can get a1+b1,while B gets a2+b2. but I don't find a way, I wonder is is there any API for me to achieve this

**Comment by zicofish** [comment]
@gogogo66 I think you are referring to Tensorflow's dataset, which supports distributed reading. You can find an example [here](https://github.com/tf-encrypted/tf-encrypted/blob/8b7cfb32c426e9a6f56769a1b47626bd1be03a66/tf_encrypted/protocol/aby3/aby3_test.py#L1039). This is not an example of reading and sharing like what you described, but hopefully you can figure out how to achieve what you want. Btw, you can also use [this](https://github.com/tf-encrypted/tf-encrypted/blob/8b7cfb32c426e9a6f56769a1b47626bd1be03a66/tf_encrypted/protocol/aby3/model/logistic_regression.py#L265), although we only use it to read from one party in our application, but you can just copy the code and put it under different `tf.device`.

**Comment by gogogo66** [comment]
你的邮件已收到
