### ISSUE TITLE
Could we use TF-encrypted for Tensorflow 2.1 or 2.2?

### ISSUE THREAD

**Issue by ymsaputra** [tf-encrypted/tf-encrypted#848]
I just wonder if the latest version of TF-encrypted is compatible with TF 2.1 or 2.2. Should we modify the codes?

**Comment by zicofish** [comment]
@ymsaputra hi, for the comment, it is not compatible with TF 2x, but it is on the way.

**Comment by ymsaputra** [comment]
Thanks
