### ISSUE TITLE
Polymorphic Encryption

### ISSUE THREAD

**Issue by tomatopuree** [tf-encrypted/tf-encrypted#851]
Hello, great library you got here!

How could I go about extending this library to polymorphic encryption? Are there any plans to do so, and if not, what would be a good angle of attack?

Thank you

**Comment by vincehong** [comment]
Hello ! Not sure what you mean by polymorphic encryption :/ 
Does it mean homomorphic encryption ? If so, you can look at https://github.com/tf-encrypted/tf-seal

**Comment by tomatopuree** [comment]
Tf-seal looks very interesting! Thank you. 

Section 1.2 of this document gives a simple overview of polymorphic encryption. 

https://eprint.iacr.org/2016/411.pdf

What I am looking for is an open source project that provides the ability to use homomorphic encryption with multiple private keys, without duplicating the encrypted data through the use of a "transcryptor".
