### ISSUE TITLE
Problem with importing "tf_encrypted"

### ISSUE THREAD

**Issue by xahmadzai** [tf-encrypted/tf-encrypted#852]
when i try to import "import tf_encrypted as tfe" it give me the following error, could anyone help me please

AttributeError: module 'tensorflow' has no attribute 'Session'

i also tried to use "tf.compat.v1.disable_eager_execution()" but it also doesn't work

**Comment by vincehong** [comment]
Currently (as far as I tested) tfe is only compatible with TF 1.x (e.g. 1.13).

**Comment by zicofish** [comment]
Close this now. Please open a new one if there is still any problem.
