### ISSUE TITLE
Version issue (AttributeError: module 'tensorflow' has no attribute 'ConfigProto')

### ISSUE THREAD

**Issue by rish2410** [tf-encrypted/tf-encrypted#859]
Hello Team, 

I am trying to import tf_encrypted but it gives me following error :

**AttributeError: module 'tensorflow' has no attribute 'ConfigProto'**

I tried to install latest version i.e. 0.5.7 but no success .

Can you please help to get this issue resolved
So that I can explore more on tf_encrypted
![image](https://user-images.githubusercontent.com/22889083/170639757-c5fc0359-1212-4dd1-84ab-38c726d347b2.png)

**Comment by zicofish** [comment]
@rish2410 Hi, seems that you are using TF 2.x?
TF-Encrypted is only tested up to TF 1.15.2, and not compatible with TF v2 at its current state.

Btw, at the time of writing, the latest version should be 0.7.0, not 0.5.7.
