### ISSUE TITLE
Implement replicated secret sharing (From ABY3)

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#86]

**Comment by ianlivingstone** [comment]
Can you add more details here @mortendahl ?

**Comment by justin1121** [comment]
Pretty good explanation of replicated secret sharing in Section 3.2.1 of the [ABY3 paper](https://eprint.iacr.org/2018/403.pdf).

**Comment by justin1121** [comment]
Some more details about the outcome of this issue:

### Motivation

The motivation behind implementing replicated secret sharing is to benchmark some models using this scheme and to learn more about adding new features/protocols to tf-encrypted.

### Outcome

Implement a new protocol which adds the ability to run basic computations with a replicated secret sharing scheme.

Below are the basic computations we should support from the beginning:

- [ ] fixed point numbers
- [ ] sharing
- [ ] recombining
- [ ] private private multiplication
- [ ] private private addition
- [ ] private private matrix multiplications
- [ ]  polynomial approximation (e.g. sigmoid, relu)

**Comment by justin1121** [comment]
Once we have these implemented and a great idea of where we want to go in the future we can extend this protocol to support things we already support in Pond.

**Comment by ianlivingstone** [comment]
@justin1121 can we add the tensor refactor as a dependency to this issue and which of the above checkboxes are blocked?

**Comment by justin1121** [comment]
None of the above check boxes are currently blocked. Ideally implementing the above will help us understand how best to tackle the tensor refactor.

**Comment by mortendahl** [comment]
Closed with https://github.com/tf-encrypted/tf-encrypted/pull/721
