### ISSUE TITLE
Can this framework use encrypted training data to train network models? Are there any relevant cases to learn from?

### ISSUE THREAD

**Issue by dikjstra** [tf-encrypted/tf-encrypted#866]

**Comment by zicofish** [comment]
@dikjstra You can first check whether [this example](https://github.com/tf-encrypted/tf-encrypted/tree/master/examples/benchmark/training) helps in your case. It uses data that is shared by one party.

Otherwise, you might have to clarify what `encrypted training data` you mean. Is it something that is already secret shared? We can definitely add more use cases if necessary. But from our experience, data is always initially owned and encrypted (secret shared) by someone.

**Comment by dikjstra** [comment]
> @dikjstra You can first check whether [this example](https://github.com/tf-encrypted/tf-encrypted/tree/master/examples/benchmark/training) helps in your case. It uses data that is shared by one party.
> 
> Otherwise, you might have to clarify what `encrypted training data` you mean. Is it something that is already secret shared? We can definitely add more use cases if necessary. But from our experience, data is always initially owned and encrypted (secret shared) by someone.


I see, there is one more question, is there a way for me to view the data transmitted from the client on the server side? Is it PondPrivateTensor?

**Comment by zicofish** [comment]
@dikjstra It is PondPrivateTensor if you use the Pond protocol. Internally, it represents two pieces of shares on two servers respectively.

**Comment by dikjstra** [comment]
> @dikjstra You can first check whether [this example](https://github.com/tf-encrypted/tf-encrypted/tree/master/examples/benchmark/training) helps in your case. It uses data that is shared by one party.
> 
> Otherwise, you might have to clarify what `encrypted training data` you mean. Is it something that is already secret shared? We can definitely add more use cases if necessary. But from our experience, data is always initially owned and encrypted (secret shared) by someone.

For example, three hospitals want to use their data to train a model, but they don't want to disclose their medical data. Can the framework implement the training of a model with their three-party encrypted data? I see the example is using the trained model to make predictions on encrypted data

**Comment by zicofish** [comment]
@dikjstra The link I provided includes `training`, not `predictions`. Please check the details. And it solves the scenario you describe.

**Comment by dikjstra** [comment]
> @dikjstra The link I provided includes `training`, not `predictions`. Please check the details. And it solves the scenario you describe.

What should I do if I want to encrypt and aggregatethe data of multiple clients to the server, and how should I configure the code of the client and server, just like [this example](https://github.com/tf-encrypted/tf-encrypted/tree/master/examples/notebooks/keras-classification)

**Comment by zicofish** [comment]
@dikjstra Check the example at [this line](https://github.com/tf-encrypted/tf-encrypted/blob/ed3e3ffc2c0e903feb1dd7faaadce32aeedd7fa9/examples/benchmark/training/private_lr_training.py#L230). Inside the class `TrainingClient`, it would load data from a device named `training-client` and encrypt (secret share) the data onto three servers (`server0`, `server1`, `server2`) that are specified in [this file](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/benchmark/training/config.json). It would help your understanding if you also take a look at how input is processed in the protocol implementation [here](https://github.com/tf-encrypted/tf-encrypted/blob/ed3e3ffc2c0e903feb1dd7faaadce32aeedd7fa9/tf_encrypted/protocol/aby3/aby3.py#L533).

**Comment by dikjstra** [comment]
> 
Hello, when I run the "b - Secure Model Serving.ipynb" of [this example](https://github.com/tf-encrypted/tf-encrypted/tree/master/examples/notebooks/keras-classification), the following error occurs：
![微信截图_20230221103733](https://user-images.githubusercontent.com/90977053/220233406-a1324d5f-7606-4205-9158-b92109a38682.png)
My environment configuration：pyhton=3.6 tensorflow=2.2 tf-encrypted=0.8.0
