### ISSUE TITLE
Scaling base question

### ISSUE THREAD

**Issue by Qi-Pang** [tf-encrypted/tf-encrypted#874]
Hi,

May I know why you use a scaling base of 3 instead of 2 in the fixed_64 configuration? 

`fixed64 = FixedpointConfig(
    scaling_base=3,
    precision_integral=7,
    precision_fractional=8,
    matmul_threshold=256,
    truncation_gap=20,
    use_noninteractive_truncation=False,
)`

https://github.com/tf-encrypted/tf-encrypted/blob/master/tf_encrypted/tensor/fixed.py#L74

Thanks!

**Comment by zicofish** [comment]
@Qi-Pang This is mainly related to [`truncation`](https://github.com/tf-encrypted/tf-encrypted/blob/9f1c0d5ab9a8e485b80cbab39dcd5a41e9d7e28a/tf_encrypted/protocol/pond/pond.py#L2366). When using interactive truncation, it requires to compute inverse, which is possible with base 3 but impossible with base 2. You might have to read the code and paper for the interactive truncation to understand this further. With that said, normally, we would NOT interactive truncation, but instead we use non-interactive truncation with `fixed64_ni`.

**Comment by Qi-Pang** [comment]
I see. Thanks a lot for the info!
