### ISSUE TITLE
windows install tf-encrypted issue

### ISSUE THREAD

**Issue by macknight** [tf-encrypted/tf-encrypted#886]
ERROR: The tar file (C:\Users\xx\AppData\Local\Temp\pip-unpack-plha6gd0\tf-encrypted-0.9.1.tar.gz) has a file (C:\Users\xx\AppData\Local\Temp\pip-install-bj8xrdtv\tf-encrypted_08c1f7c5ab8c46a19975b7aaec907caf\tf_encrypted/operations/aux) trying to install outside target directory (C:\Users\xx\AppData\Local\Temp\pip-install-bj8xrdtv\tf-encrypted_08c1f7c5ab8c46a19975b7aaec907caf)

**Comment by macknight** [comment]
Can't I install it in windows OS?

**Comment by vincehong** [comment]
Sorry but the benchmarks are only tested on Linux (Ubuntu)
