### ISSUE TITLE
WAN setting benchmarks.

### ISSUE THREAD

**Issue by DuanYuFi** [tf-encrypted/tf-encrypted#894]
Hi, I am trying to run some WAN setting benchmarks according to [this](https://github.com/tf-encrypted/tf-encrypted/blob/master/docs/RUNNING.md). I want to let the parties jointly compute the dot-product of provided data. Here's how I did:

First, the task is described as follows:
```python
import tensorflow as tf
import tf_encrypted as tfe
from tf_encrypted.protocol import ABY3

config = tfe.RemoteConfig.load('config.json')
print("Loaded config")
config.connect_servers()
print("Connected servers")
tfe.set_config(config)
print("Set config")
tfe.set_protocol(ABY3())
print("Set protocol")
TEST_SIZE = 100

@tfe.local_computation("input-provider-x")
def provide_input_x():
    # return randint in [0, 0xff] with size = TEST_SIZE // 2
    return tf.random.uniform(shape=(TEST_SIZE,), minval=0, maxval=0xff, dtype=tf.int32)

@tfe.local_computation("input-provider-y")
def provide_input_y():
    # return randint in [0, 0xff] with size = TEST_SIZE // 2
    return tf.random.uniform(shape=(TEST_SIZE,), minval=0, maxval=0xff, dtype=tf.int32)

def main():
    x = provide_input_x()
    y = provide_input_y()

    result = (x * y).sum()

    print(result.reveal().to_native())

if __name__ == "__main__":
    main()
```

where `config.json` is:

```json
{
    "server0": "172.20.126.23:4440",
    "server1": "172.20.126.25:4440",
    "server2": "172.20.126.24:4440",
    "input-provider-x": "172.20.126.23:4441",
    "input-provider-y": "172.20.126.25:4441",
}
```
Then, I started the servers and providers in the corresponding machines. Finally, I ran `python main.py`. But it stucked at `config.connect_servers()`. Why it happens?

**Comment by DuanYuFi** [comment]
Solved. The config from one server has a redundant item about output, which is not used in the task and of course not started the corresponding node. And it makes the function `connect_servers` stucked. Thanks.

**Comment by junzlovegood** [comment]
Hello, I ran the code according to your configuration, but finally got stuck at config.connect_servers(), is there any modification behind your above code and configuration?

**Comment by DuanYuFi** [comment]
Hi, 
Are you running this code on different machines? If so, please make sure:
1. Modify the ip configurations to your ip addresses.
2. Make sure you have startup these nodes on corresponding machines.
3. Make sure the configuration file is the same on different machines.

**Comment by junzlovegood** [comment]
Hi, thanks for the answer.
My code is running on three different servers, with corresponding services enabled on the servers according to the configuration.
I rechecked the configuration according to your tips. But it still doesn't work.

When I check the network, I find that it is always waiting for a connection, so I guess there is something wrong with my network.
`COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python  11187 ubuntu    6u  IPv6  74001      0t0  TCP *:4441 (LISTEN)
python  11944 ubuntu   26u  IPv6  74540      0t0  TCP VM-32-200-ubuntu:46150->175.27.25.791:4441 (SYN_SENT)
python  11944 ubuntu   28u  IPv6  74542      0t0  TCP VM-32-200-ubuntu:52458->43.137.492.911:4441 (SYN_SENT)`
